/*
 * This library is part of OpenCms -
 * the Open Source Content Management System
 *
 * Copyright (c) Alkacon Software GmbH & Co. KG (https://www.alkacon.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * For further information about Alkacon Software, please see the
 * company website: https://www.alkacon.com
 *
 * For further information about OpenCms, please see the
 * project website: https://www.opencms.org
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package org.opencms.ade.contenteditor.client;

import org.opencms.gwt.client.ui.CmsPopup;
import org.opencms.gwt.client.ui.CmsPushButton;

import com.google.gwt.core.client.GWT;
import com.google.gwt.uibinder.client.UiBinder;
import com.google.gwt.uibinder.client.UiField;
import com.google.gwt.user.client.ui.HTML;
import com.google.gwt.user.client.ui.Panel;

/**
 * Dialog to display an HTML status message generated by the content augmentation.
 */
public class CmsAugmentationFeedbackDialog extends CmsPopup {

    /**
     * UiBinder interface for this dialog.<p>
     */
    interface I_UiBinder extends UiBinder<Panel, CmsAugmentationFeedbackDialog> {
        // empty uibinder interface
    }

    /** UiBinder instance for this dialog. */
    private static I_UiBinder uibinder = GWT.create(I_UiBinder.class);

    /** The root widget.*/
    private Panel m_root;

    /** The actual field containing the HTML. */
    @UiField
    protected HTML m_html;

    /**
     * Creates a new instance.
     *
     * @param title the title
     * @param htmlMessage the HTML message to display
     */
    public CmsAugmentationFeedbackDialog(String caption, String htmlMessage) {

        super(CmsPopup.WIDE_WIDTH);
        m_root = uibinder.createAndBindUi(this);
        m_html.setHTML(htmlMessage);
        CmsPushButton okButton = new CmsPushButton();
        setModal(true);
        setMainContent(m_root);
        setCaption(caption);
        okButton.setText(org.opencms.gwt.client.Messages.get().key(org.opencms.gwt.client.Messages.GUI_OK_0));
        okButton.setUseMinWidth(true);
        okButton.addClickHandler(event -> {
            CmsAugmentationFeedbackDialog.this.hide();
        });
        addButton(okButton);

    }

}
