#
# clear text name
##############################################################################
oracle19c.name=Oracle 19c, 21c, 23ai & 26ai

#
# Alkacon OpenCms driver classes
##############################################################################
oracle19c.vfs.driver=org.opencms.db.oracle.CmsVfsDriver
oracle19c.user.driver=org.opencms.db.oracle.CmsUserDriver
oracle19c.project.driver=org.opencms.db.oracle.CmsProjectDriver
oracle19c.history.driver=org.opencms.db.oracle.CmsHistoryDriver
oracle19c.subscription.driver=org.opencms.db.oracle.CmsSubscriptionDriver

#
# validation query
##############################################################################
#oracle19c.testQuery=SELECT SYSDATE FROM DUAL;
#oracle19c.testQuery=SELECT * FROM CMS_OFFLINE_PROPERTYDEF WHERE PROPERTYDDEF_NAME = 'Title'
oracle19c.testQuery=SELECT 1 FROM DUAL

#
# JDBC driver
##############################################################################
oracle19c.driver=oracle.jdbc.driver.OracleDriver

#
# JDBC connect string
##############################################################################
oracle19c.constr=jdbc:oracle:thin:@localhost:1521/opencms
oracle19c.constr.params=

#
# database user
##############################################################################
oracle19c.user=system

#
# tablespaces used when creating an oracle user
##############################################################################
oracle19c.defaultTablespace=users
oracle19c.indexTablespace=users
oracle19c.temporaryTablespace=temp

#
# ranking used for setup select box
##############################################################################
oracle19c.ranking=290

#
# SQL manager class
##############################################################################
oracle19c.sqlmanager=org.opencms.db.oracle.CmsSqlManager

#
# Jdbc Drivers - Comma separated list of jars
##############################################################################
oracle19c.libs=ojdbc11-23.26.1.0.0.jar

#
# Separator - the separator for the connect String of the db
##############################################################################
oracle19c.separator=
