/*
 * File   : $Source: /alkacon/cvs/opencms/src/org/opencms/report/A_CmsReport.java,v $
 * Date   : $Date: 2004/02/16 01:30:51 $
 * Version: $Revision: 1.8 $
 *
 * This library is part of OpenCms -
 * the Open Source Content Mananagement System
 *
 * Copyright (C) 2002 - 2003 Alkacon Software (http://www.alkacon.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * For further information about Alkacon Software, please see the
 * company website: http://www.alkacon.com
 *
 * For further information about OpenCms, please see the
 * project website: http://www.opencms.org
 * 
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 */

package org.opencms.report;

import org.opencms.i18n.CmsMessages;
import org.opencms.util.CmsStringSubstitution;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * Base report class.<p> 
 * 
 * @author Alexander Kandzior (a.kandzior@alkacon.com)  
 * @author Thomas Weckert (t.weckert@alkacon.com)
 * @version $Revision: 1.8 $
 */
public abstract class A_CmsReport implements I_CmsReport {

    /** Localized message access object */
    private List m_messages;
    
    /** Runtime of the report */
    private long m_starttime;
    
    /** Contains all error messages generated by the report */
    private List m_errors = new ArrayList();
    
    /**
     * @see org.opencms.report.I_CmsReport#addBundle(String, Locale)
     */
    public void addBundle(String bundleName, Locale locale) {
        CmsMessages msg = new CmsMessages(bundleName, locale);
        if (m_messages.contains(msg)) {
            m_messages.remove(msg);
        }
        m_messages.add(msg);   
    }
    
    /**
     * @see org.opencms.report.I_CmsReport#addError(java.lang.Object)
     */
    public void addError(Object obj) {
        m_errors.add(obj);
    }
    
    /**
     * @see org.opencms.report.I_CmsReport#getErrors()
     */
    public List getErrors() {
        return m_errors;
    }
     
    /**
     * @see org.opencms.report.I_CmsReport#getRuntime()
     */     
    public long getRuntime() {
        return System.currentTimeMillis() - m_starttime;
    }
    
    /**
     * @see org.opencms.report.I_CmsReport#hasError()
     */
    public boolean hasError() {
        return (m_errors.size() > 0);
    }
    
    /**
     * Initializes some member variables for this report.<p>
     */
    protected void init() {
        m_starttime = System.currentTimeMillis();
        m_messages = new ArrayList();
    }
    
    /**
     * @see org.opencms.report.I_CmsReport#key(java.lang.String)
     */
    public String key(String keyName) {
        for (int i=0, l=m_messages.size(); i < l; i++) {
            CmsMessages msg = (CmsMessages)m_messages.get(i);
            String key = msg.key(keyName, (i < (l-1)));
            if (key != null) {
                return key;
            }
        }         
        // if not found, check in 
        return CmsMessages.formatUnknownKey(keyName);
    }
    
    /**
     * @see org.opencms.report.I_CmsReport#formatRuntime()
     */
    public String formatRuntime() {
        return CmsStringSubstitution.formatRuntime(getRuntime());
    }
    
    /**
     * @see org.opencms.report.I_CmsReport#resetRuntime()
     */
    public void resetRuntime() {
        m_starttime = System.currentTimeMillis();
    }
}