dependencies {

    // internal source set dependencies
    modulesCompile sourceSets.main.output
    setupCompile sourceSets.main.output
    gwtCompile sourceSets.main.output
    gwtCompile sourceSets.modules.output
    testCompile sourceSets.setup.output
    testCompile sourceSets.modules.output
    testCompile sourceSets.gwt.output
    testGwtCompile sourceSets.main.output
    testGwtCompile sourceSets.modules.output
    testGwtCompile sourceSets.gwt.output

    gwtCompile('ant:ant:1.6.5') { transitive = false }
    gwtCompile('colt:colt:1.2.0') { transitive = false }
    gwtCompile('com.google.code.gson:gson:2.10.1') { transitive = false }
    gwtCompile('org.gwtproject:gwt-dev:2.13.1') {
        exclude group: 'xml-apis', module: 'xml-apis'
    }
    gwtCompile('org.gwtproject:gwt-user:2.13.1')
    gwtCompile('com.google.jsinterop:jsinterop-annotations:2.0.2') { transitive = false }
    gwtCompile('com.google.jsinterop:jsinterop-annotations:1.0.2') {
        transitive = false
        artifact {
            name = 'jsinterop-annotations'
            type = 'jar'
        }
        artifact {
            name = 'jsinterop-annotations'
            type = 'jar'
            classifier = 'sources'
        }
    }
    gwtCompile('com.vaadin:vaadin-compatibility-client:8.14.3') { transitive = false }
    gwtCompile('com.vaadin:vaadin-client:8.14.3') { transitive = false }
    gwtCompile('com.vaadin:vaadin-client-compiler:8.14.3') { transitive = false }
    gwtCompile('com.vaadin:vaadin-sass-compiler:0.9.13') { transitive = false }
    gwtCompile('com.vaadin.external.flute:flute:1.3.0.gg2') { transitive = false }
    gwtCompile('com.yahoo.platform.yui:yuicompressor:2.4.8') { transitive = false }
    gwtCompile('javax.validation:validation-api:1.0.0.GA') {
        transitive = false
        artifact {
            name = 'validation-api'
            type = 'jar'
        }
        artifact {
            name = 'validation-api'
            type = 'jar'
            classifier = 'sources'
        }
    }
    gwtCompile('org.ow2.asm:asm-commons:9.3') { transitive = false }
    gwtCompile('org.ow2.asm:asm-util:9.3') { transitive = false }
    gwtCompile('org.ow2.asm:asm-tree:9.3') { transitive = false }
    gwtCompile('org.timepedia.exporter:gwtexporter:2.5.1') { transitive = false }
    gwtCompile('org.w3c.css:sac:1.3') { transitive = false }
    gwtCompile('tapestry:tapestry:4.0.2') { transitive = false }
    distribution('antlr:antlr:2.7.7') { transitive = false }
    distribution('com.adobe.xmp:xmpcore:6.1.11') { transitive = false }
    distribution('com.alkacon:alkacon-simapi:1.0.4') { transitive = false }
    distribution('com.alkacon:alkacon-diff:0.9.2') { transitive = false }
    distribution('com.cybozu.labs:langdetect:1.1-20120112') { transitive = false }
    distribution('com.drewnoakes:metadata-extractor:2.18.0') { transitive = false }
    distribution('com.fasterxml.jackson.core:jackson-core:2.18.0') { transitive = false }
    distribution('com.fasterxml.jackson.core:jackson-annotations:2.18.0') { transitive = false }
    distribution('com.fasterxml.jackson.core:jackson-databind:2.18.0') { transitive = false }
    distribution('com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.18.0') { transitive = false }
    distribution('com.github.ben-manes.caffeine:caffeine:3.1.8') { transitive = false }
    distribution('com.github.jai-imageio:jai-imageio-core:1.4.0') { transitive = false }
    distribution('com.github.jai-imageio:jai-imageio-jpeg2000:1.3.0') { transitive = false }
    distribution('com.github.librepdf:openpdf:1.3.20') { transitive = false }
    distribution('com.google.guava:guava:33.5.0-jre')
    distribution('com.google.guava:guava-gwt:33.5.0-jre')
    distribution('com.google.jsinterop:base:1.0.3') { transitive = false }
    distribution('com.google.code.findbugs:jsr305:3.0.2') { transitive = false }
    distribution('org.jspecify:jspecify:0.3.0') { transitive = false }
    distribution('com.google.elemental2:elemental2-promise:1.2.3') { transitive = false }
    distribution('com.google.elemental2:elemental2-core:1.2.3') { transitive = false }
    distribution('com.google.elemental2:elemental2-dom:1.2.3') { transitive = false }
    distribution('com.google.elemental2:elemental2-webstorage:1.2.3') { transitive = false }

    distribution('com.google.gwt:gwt-elemental:2.9.0') { transitive = false }
    distribution('com.google.code.gson:gson:2.10.1') { transitive = false }
    distribution('com.googlecode.json-simple:json-simple:1.1.1') { transitive = false }
    distribution('com.ibm.icu:icu4j:77.1') { transitive = false } //for solr-analysis-extras
    distribution('org.json:json:20240303') { transitive = false }
    distribution('com.lambdaworks:scrypt:1.4.0') { transitive = false }
    distribution('com.sun.mail:javax.mail:1.6.2') { transitive = false }
    distribution('com.sun.xml.bind:jaxb-impl:2.2.11') { transitive = false }
    distribution('com.sun.xml.bind:jaxb-core:2.2.11') { transitive = false }
    distribution('com.sun.xml.messaging.saaj:saaj-impl:1.3.28') { transitive = false }
    distribution('com.sun.xml.stream.buffer:streambuffer:2.0.0-M2') { transitive = false }
    distribution('com.vaadin:vaadin-compatibility-server:8.14.3') { transitive = false }
    distribution('com.vaadin:vaadin-server:8.14.3') { transitive = false }
    distribution('com.vaadin:vaadin-compatibility-shared:8.14.3') { transitive = false }
    distribution('com.vaadin:vaadin-push:8.14.3') { transitive = false }
    distribution('com.vaadin:vaadin-shared:8.14.3') { transitive = false }
    distribution('com.vaadin:vaadin-themes:8.14.3') { transitive = false }
    distribution('com.vaadin.external:gentyref:1.2.0.vaadin1') { transitive = false }
    distribution('com.zaxxer:HikariCP:6.2.1') { transitive = false }
    // used by Apache POI
    distribution('com.zaxxer:SparseBitSet:1.2') { transitive = false }
    distribution('commons-logging:commons-logging:1.3.6') { transitive = false }
    distribution('commons-beanutils:commons-beanutils:1.11.0') { transitive = false }
    distribution('commons-codec:commons-codec:1.21.0') { transitive = false }
    distribution('commons-collections:commons-collections:3.2.2') { transitive = false }
    distribution('org.apache.commons:commons-fileupload2-core:2.0.0-M5') { transitive = false }
    distribution('commons-io:commons-io:2.21.0') { transitive = false }
    //distribution('cryptix.jce:crytix-jce-provider:20050328') { transitive = false }
    distribution('de.malkusch.whois-server-list:public-suffix-list:2.2.0') { transitive = false }
    distribution('dev.langchain4j:langchain4j-open-ai:1.9.1')
    distribution('com.deepl.api:deepl-java:1.14.0')
    //for Solr
    distribution('jakarta.activation:jakarta.activation-api:2.1.3') { transitive = false }
    distribution('jakarta.validation:jakarta.validation-api:3.0.2') { transitive = false }
    distribution('javax.validation:validation-api:1.0.0.GA') { transitive = false }
    distribution('javax.activation:activation:1.1.1') { transitive = false }
    distribution('javax.xml.bind:jaxb-api:2.1') { transitive = false }
    distribution('jaxen:jaxen:1.2.0') { transitive = false }
    distribution('joda-time:joda-time:2.10.6') { transitive = false }
    distribution('net.arnx:jsonic:1.3.10') { transitive = false }
    distribution('net.sf.opencsv:opencsv:2.3') { transitive = false }
    distribution('net.sourceforge.nekohtml:nekohtml:1.9.22') { transitive = false }
    distribution('net.sourceforge.serp:serp:1.13.1') { transitive = false }
    distribution('org.antlr:antlr-runtime:3.5.2') { transitive = false }
    distribution('org.antlr:stringtemplate:3.2.1') { transitive = false }
    distribution('org.antlr:ST4:4.0.8') { transitive = false }
    constraints {
        distribution('org.apache.cxf:cxf-core:3.5.11')
        distribution('org.apache.cxf:cxf-rt-bindings-soap:3.5.11')
        distribution('org.apache.cxf:cxf-rt-bindings-xml:3.5.11')
        distribution('org.apache.cxf:cxf-rt-databinding-jaxb:3.5.11')
        distribution('org.apache.cxf:cxf-rt-frontend-jaxws:3.5.11')
        distribution('org.apache.cxf:cxf-rt-frontend-simple:3.5.11')
        distribution('org.apache.cxf:cxf-rt-transports-http:3.5.11')
        distribution('org.apache.cxf:cxf-rt-ws-addr:3.5.11')
        distribution('org.apache.cxf:cxf-rt-ws-policy:3.5.11')
        distribution('org.apache.cxf:cxf-rt-wsdl:3.5.11')
    }

    distribution('org.apache.commons:commons-email:1.5') { transitive = false }
    distribution('org.apache.commons:commons-exec:1.4.0') { transitive = false }
    distribution('org.apache.commons:commons-compress:1.28.0') { transitive = false }
    distribution('org.apache.commons:commons-collections4:4.5.0') { transitive = false }
    distribution('org.apache.commons:commons-digester3:3.2') { transitive = false }
    distribution('org.apache.commons:commons-lang3:3.20.0') { transitive = false }
    distribution('org.apache.commons:commons-math3:3.6.1') { transitive = false }
    distribution('org.apache.commons:commons-pool2:2.8.1') { transitive = false }
    distribution('org.apache.commons:commons-text:1.10.0') { transitive = false }
    distribution('org.apache.httpcomponents:httpclient:4.5.14') { transitive = false }
    distribution('org.apache.httpcomponents:httpcore:4.4.16') { transitive = false }
    distribution('org.apache.httpcomponents:httpmime:4.5.14') { transitive = false }
    
    distribution('org.apache.logging.log4j:log4j-api:2.25.3') { transitive = false }
    distribution('org.apache.logging.log4j:log4j-core:2.25.3') { transitive = false }
    distribution('org.apache.logging.log4j:log4j-slf4j2-impl:2.25.3') { transitive = false }
    distribution('org.apache.logging.log4j:log4j-jcl:2.25.3') { transitive = false }
//    distribution('org.apache.lucene:lucene-analysis-common:10.3.2')
    distribution('org.apache.lucene:lucene-core:10.3.2')
    distribution('org.apache.lucene:lucene-highlighter:10.3.2')
    distribution('org.apache.lucene:lucene-queryparser:10.3.2')
    distribution('org.apache.solr:solr-analysis-extras:10.0.0')
    distribution('org.apache.solr:solr-core:10.0.0')
    distribution('org.apache.solr:solr-solrj:10.0.0')
    distribution('org.apache.solr:solr-solrj-jetty:10.0.0') // for solr http client
    distribution('org.apache.pdfbox:fontbox:2.0.32') { transitive = false }
    distribution('org.apache.pdfbox:jempbox:1.8.17') { transitive = false }
    distribution('org.apache.pdfbox:pdfbox:2.0.32') { transitive = false }
    distribution('org.apache.pdfbox:pdfbox-tools:2.0.32') { transitive = false }
    distribution('org.apache.tika:tika-core:3.2.3')
    distribution('org.apache.tika:tika-parser-microsoft-module:3.2.3')
    distribution('org.apache.tika:tika-parser-pdf-module:3.2.3')
    distribution('org.apache.xbean:xbean-asm5-shaded:4.5') { transitive = false }
    distribution('org.apache.xmlbeans:xmlbeans:5.1.1') { transitive = false }
    distribution('org.apache.xmlgraphics:batik-constants:1.16') { transitive = false }
    distribution('org.apache.xmlgraphics:batik-css:1.16') { transitive = false }
    distribution('org.apache.xmlgraphics:batik-i18n:1.16') { transitive = false }
    distribution('org.apache.xmlgraphics:batik-util:1.16') { transitive = false }
    distribution('org.bouncycastle:bcpkix-jdk18on:1.79') { transitive = false }
    distribution('org.bouncycastle:bcprov-jdk18on:1.79') { transitive = false }
    distribution('org.bouncycastle:bcutil-jdk18on:1.79') { transitive = false }
    distribution('org.codehaus.mojo:animal-sniffer-annotations:1.19') { transitive = false }
    distribution('org.dom4j:dom4j:2.1.4') { transitive = false }

    distribution('org.hibernate:jtidy:r8-20060801') { transitive = false }
    distribution('org.htmlparser:htmlparser:2.1') { transitive = false }
    distribution('org.htmlparser:htmllexer:2.1') { transitive = false }
    distribution('org.htmlunit:neko-htmlunit:4.6.0') { transitive = false }
    distribution('com.github.kwart.jsign:jsign-jpedal:4.92.13') { transitive = false }
    distribution('org.javassist:javassist:3.30.2-GA') { transitive = false }
    distribution('org.jsoup:jsoup:1.21.2') { transitive = false }
    distribution('org.jvnet.mimepull:mimepull:1.9.13') { transitive = false }
    distribution('org.locationtech.spatial4j:spatial4j:0.8') { transitive = false }
    distribution('org.ow2.asm:asm:9.3') { transitive = false }
    distribution('org.owasp.antisamy:antisamy:1.7.7') { transitive = false }
    distribution('org.quartz-scheduler:quartz:2.3.2') { transitive = false }
    distribution('org.safehaus.jug:jug:2.0.0:lgpl') { transitive = false }
    distribution('org.restlet.jee:org.restlet:2.3.12') { transitive = false }
    distribution('org.rrd4j:rrd4j:3.7') { transitive = false }
    distribution('org.slf4j:slf4j-api:2.0.13') { transitive = false }
    distribution('org.slf4j:jul-to-slf4j:2.0.13') { transitive = false }
    distribution('org.tepi.filtertable:filteringtable:1.0.1.v8') { transitive = false }
    distribution('org.vaadin.addons:popupbutton:3.0.0') { transitive = false }
    distribution('org.xhtmlrenderer:flying-saucer-core:9.1.20') { transitive = false }
    distribution('org.xhtmlrenderer:flying-saucer-pdf-openpdf:9.1.20') { transitive = false }
    distribution('oro:oro:2.0.8') { transitive = false }
    distribution('wsdl4j:wsdl4j:1.6.3') { transitive = false }
    distribution('org.apache.servicemix.bundles:org.apache.servicemix.bundles.xalan:2.7.2_3') { transitive = false }
    distribution('xerces:xercesImpl:2.12.2') { transitive = false }
    //distribution('xml-apis:xml-apis:1.4.01') { transitive = false }
    distribution('dev.samstevens.totp:totp:1.7.1')
    distribution('software.amazon.awssdk:apache-client:2.42.29') { transitive = true }
    distribution('software.amazon.awssdk:s3:2.42.29') { transitive = true }
    // http://svn.alfresco.com/repos/alfresco-open-mirror/alfresco/HEAD/root/projects/alfresco-jlan/
    // Revision r55007
    distribution files('lib/runtime/jlan.jar')

    tlddocTool('taglibrarydoc:tlddoc:1.3') { transitive = false }

    testCompile('dumbster:dumbster:1.6') { transitive = false }
    testCompile('junit:junit:4.13.1') { transitive = false }
    testCompile('org.hamcrest:hamcrest-core:1.3') { transitive = false }
    testCompile('org.hsqldb:hsqldb:2.7.2:jdk8') { transitive = false }
    testCompile('com.oracle.database.jdbc:ojdbc11:23.26.1.0.0') { transitive = false }
    testCompile fileTree(dir: 'webapp/WEB-INF/setupdata/database', include: ['**/*.jar'], exclude: ['oracle/ojdbc14-10.2.0.3.jar'])
    // JUnit 6 Jupiter support
    testCompile platform('org.junit:junit-bom:6.0.0')
    testCompile 'org.junit.jupiter:junit-jupiter-api'
    testCompile 'org.junit.jupiter:junit-jupiter-engine'
    testCompile 'org.junit.vintage:junit-vintage-engine'
    testCompile 'org.junit.platform:junit-platform-launcher'
    testCompile 'org.junit.platform:junit-platform-suite'
    testGwtCompile('junit:junit:4.13.1') { transitive = false }
    testGwtCompile('net.sourceforge.htmlunit:htmlunit-cssparser:1.13.0') { transitive = false }
    testGwtCompile('org.brotli:dec:0.1.2') { transitive = false }
    testGwtCompile('net.sourceforge.htmlunit:neko-htmlunit:2.69.0') { transitive = false }
    testGwtCompile('net.sourceforge.htmlunit:htmlunit:2.69.0') { transitive = false }
    testGwtCompile('net.sourceforge.htmlunit:htmlunit-xpath:2.69.0') { transitive = false }
    testGwtCompile('net.sourceforge.htmlunit:htmlunit-core-js:2.69.0') { transitive = false }
    testGwtCompile('org.eclipse.jetty:apache-jsp:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty:jetty-annotations:9.4.50.v20221201') {
        transitive = false

        artifact {
            name = 'jetty-annotations'
            type = 'jar'
        }
        artifact {
            name = 'jetty-annotations'
            type = 'jar'
            classifier = 'sources'
        }
    }
    testGwtCompile('org.eclipse.jetty:jetty-continuation:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty:jetty-jndi:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty:jetty-plus:9.4.50.v20221201') {
        transitive = false
        artifact {
            name = 'jetty-plus'
            type = 'jar'
        }
        artifact {
            name = 'jetty-plus'
            type = 'jar'
            classifier = 'sources'
        }
    }
    testGwtCompile('org.eclipse.jetty:jetty-security:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty:jetty-server:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty:jetty-servlet:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty:jetty-servlets:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty:jetty-webapp:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty:jetty-xml:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty.websocket:websocket-api:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty.websocket:websocket-client:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty.websocket:websocket-common:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty.websocket:websocket-server:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.eclipse.jetty.websocket:websocket-servlet:9.4.50.v20221201') { transitive = false }
    testGwtCompile('org.mortbay.jasper:apache-jsp:8.0.33') { transitive = false }
}

configurations.all {
    exclude group: 'org.apache.lucene', module: 'lucene-analysis-kuromoji'
    exclude group: 'org.apache.lucene', module: 'lucene-analysis-nori'
    exclude group: 'org.apache.lucene', module: 'lucene-analysis-morfologik'
    exclude group: 'org.apache.lucene', module: 'lucene-analysis-smartcn'
    exclude group: 'org.apache.lucene', module: 'lucene-analysis-opennlp'
    exclude group: 'org.apache.opennlp', module: 'opennlp-tools'
    exclude group: 'org.eclipse.jetty.toolchain', module: 'jetty-servlet-api'
    exclude group: 'com.microsoft.onnxruntime', module: 'onnxruntime'
    exclude group: 'io.netty'
}
