pluginManagement {
    repositories {
        maven {
            url = uri('https://repository-cdn.liferay.com/nexus/content/groups/public')
        }
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
    resolutionStrategy {
        eachPlugin {
            if (requested.id.id.startsWith('org.opencms.modules')) {
                useModule('org.opencms:opencms-gradle-plugin:4.+')
            }
        }
    }
}

def external_directories = startParameter.projectProperties['external_directories']
if (null != external_directories) {
    include external_directories
    project(':' + external_directories).name = 'extmodules'
    gradle.ext.withcore = 'true'
}
def variant = providers.gradleProperty("opencms_variant").orElse("").map(v -> v ? "-$v" : "").get()
rootProject.name = "opencms-core${variant}"


