function editprovider(){var P='',wb='" for "gwt:onLoadErrorFn"',ub='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',Nb='&',oc='.cache.html',_='/',dc='1C869C848E5F5540F06A72E18140296B',fc='21E66CBB6C05AFCAA54D95EE72406BC9',kc='32226DCD4D663B75C41BCA530B25ABA9',nc=':',ec=':1',gc=':2',hc=':3',ic=':4',jc=':5',ob='::',qc='<script defer="defer">editprovider.onInjectionDone(\'editprovider\')<\/script>',hb='<script id="',rb='=',$='?',tb='Bad handler "',lc='D30BF0856BC1A42723E5C3BEAE4A3E1D',mc='D6F9FDF7729CC6B545640815DD225586',pc='DOMContentLoaded',jb='SCRIPT',Qb='Unexpected exception in locale detection, using default: ',Pb='_',Ob='__gwt_Locale',gb='__gwt_marker_editprovider',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',qb='content',cc='de',Q='editprovider',eb='editprovider.nocache.js',nb='editprovider::',Lb='en',Y='end',Eb='file',Ib='fileapi',Bb='fileapi.support',Hb='formdata',Fb='function',Yb='gecko',Zb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',vb='gwt:onLoadErrorFn',sb='gwt:onPropertyErrorFn',pb='gwt:property',ac='hosted.html?editprovider',Xb='ie6',Wb='ie8',xb='iframe',ab='img',Cb='input',yb="javascript:''",_b='loadExternalRefs',Kb='locale',Mb='locale=',lb='meta',Ab='moduleRequested',X='moduleStartup',Vb='msie',mb='name',Jb='no',Gb='object',Sb='opera',zb='position:absolute;width:0;height:0;border:none',Ub='safari',db='script',bc='selectingPermutation',R='startup',Db='type',fb='undefined',$b='unknown',Rb='user.agent',Tb='webkit';var l=window,m=document,n=l.__gwtStatsEvent?function(a){return l.__gwtStatsEvent(a)}:null,o=l.__gwtStatsSessionId?l.__gwtStatsSessionId:null,p,q,r,s=P,t={},u=[],v=[],w=[],x=0,y,z;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!l.__gwt_stylesLoaded){l.__gwt_stylesLoaded={}}if(!l.__gwt_scriptsLoaded){l.__gwt_scriptsLoaded={}}function A(){var b=false;try{var c=l.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||l.external&&l.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}A=function(){return b};return b}
function B(){if(p&&q){var b=m.getElementById(Q);var c=b.contentWindow;if(A()){c.__gwt_getProperty=function(a){return H(a)}}editprovider=null;c.gwtOnLoad(y,Q,s,x);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function C(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=m.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=m.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;m.write(hb+b+ib);c=m.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=m.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
var k=g();if(k==P){k=h()}if(k==P){k=i()}if(k==P){k=j()}if(k==P){k=e(m.location.href)}k=f(k);s=k;return k}
function D(){var b=document.getElementsByTagName(lb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(mb),g;if(f){f=f.replace(nb,P);if(f.indexOf(ob)>=0){continue}if(f==pb){g=e.getAttribute(qb);if(g){var h,i=g.indexOf(rb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}t[f]=h}}else if(f==sb){g=e.getAttribute(qb);if(g){try{z=eval(g)}catch(a){alert(tb+g+ub)}}}else if(f==vb){g=e.getAttribute(qb);if(g){try{y=eval(g)}catch(a){alert(tb+g+wb)}}}}}}
function E(a,b){return b in u[a]}
function F(a){var b=t[a];return b==null?null:b}
function G(a,b){var c=w;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=v[a](),c=u[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(z){z(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=m.createElement(xb);a.src=yb;a.id=Q;a.style.cssText=zb;a.tabIndex=-1;m.body.appendChild(a);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Ab});a.contentWindow.location.replace(s+L)}}
v[Bb]=function(){var a=document.createElement(Cb);a.setAttribute(Db,Eb);if(a.files!=null){if(typeof FileReader==Fb||typeof FileReader==Gb){if(typeof FormData==Fb||typeof FormData==Gb){return Hb}return Ib}}return Jb};u[Bb]={fileapi:0,formdata:1,no:2};v[Kb]=function(){var b=null;var c=Lb;try{if(!b){var d=location.search;var e=d.indexOf(Mb);if(e>=0){var f=d.substring(e+7);var g=d.indexOf(Nb,e);if(g<0){g=d.length}b=d.substring(e+7,g)}}if(!b){b=F(Kb)}if(!b){b=l[Ob]}if(b){c=b}while(b&&!E(Kb,b)){var h=b.lastIndexOf(Pb);if(h<0){b=null;break}b=b.substring(0,h)}}catch(a){alert(Qb+a)}l[Ob]=c;return b||Lb};u[Kb]={de:0,'default':1,en:2};v[Rb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(b.indexOf(Sb)!=-1){return Sb}else if(b.indexOf(Tb)!=-1){return Ub}else if(b.indexOf(Vb)!=-1){if(document.documentMode>=8){return Wb}else{var d=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(d&&d.length==3){var e=c(d);if(e>=6000){return Xb}}}}else if(b.indexOf(Yb)!=-1){return Zb}return $b};u[Rb]={gecko1_8:0,ie6:1,ie8:2,opera:3,safari:4};editprovider.onScriptLoad=function(){if(I){q=true;B()}};editprovider.onInjectionDone=function(){p=true;n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:_b,millis:(new Date).getTime(),type:Y});B()};D();C();var K;var L;if(A()){if(l.external&&(l.external.initModule&&l.external.initModule(Q))){l.location.reload();return}L=ac;K=P}n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:bc});if(!A()){try{G([Jb,cc,Xb],dc);G([Jb,Lb,Xb],dc+ec);G([Ib,cc,Sb],fc);G([Hb,cc,Sb],fc);G([Jb,cc,Sb],fc);G([Ib,Lb,Sb],fc+ec);G([Hb,Lb,Sb],fc+ec);G([Jb,Lb,Sb],fc+ec);G([Ib,cc,Sb],fc+gc);G([Hb,cc,Sb],fc+gc);G([Jb,cc,Sb],fc+gc);G([Ib,Lb,Sb],fc+hc);G([Hb,Lb,Sb],fc+hc);G([Jb,Lb,Sb],fc+hc);G([Ib,cc,Sb],fc+ic);G([Hb,cc,Sb],fc+ic);G([Jb,cc,Sb],fc+ic);G([Ib,Lb,Sb],fc+jc);G([Hb,Lb,Sb],fc+jc);G([Jb,Lb,Sb],fc+jc);G([Ib,cc,Zb],kc);G([Hb,cc,Zb],kc);G([Jb,cc,Zb],kc);G([Ib,Lb,Zb],kc+ec);G([Hb,Lb,Zb],kc+ec);G([Jb,Lb,Zb],kc+ec);G([Ib,cc,Zb],kc+gc);G([Hb,cc,Zb],kc+gc);G([Jb,cc,Zb],kc+gc);G([Ib,Lb,Zb],kc+hc);G([Hb,Lb,Zb],kc+hc);G([Jb,Lb,Zb],kc+hc);G([Ib,cc,Zb],kc+ic);G([Hb,cc,Zb],kc+ic);G([Jb,cc,Zb],kc+ic);G([Ib,Lb,Zb],kc+jc);G([Hb,Lb,Zb],kc+jc);G([Jb,Lb,Zb],kc+jc);G([Hb,cc,Ub],lc);G([Jb,cc,Ub],lc);G([Hb,Lb,Ub],lc+ec);G([Jb,Lb,Ub],lc+ec);G([Hb,cc,Ub],lc+gc);G([Jb,cc,Ub],lc+gc);G([Hb,Lb,Ub],lc+hc);G([Jb,Lb,Ub],lc+hc);G([Jb,cc,Wb],mc);G([Jb,Lb,Wb],mc+ec);K=w[H(Bb)][H(Kb)][H(Rb)];var M=K.indexOf(nc);if(M!=-1){x=Number(K.substring(M+1));K=K.substring(0,M)}L=K+oc}catch(a){return}}var N;function O(){if(!r){r=true;B();if(m.removeEventListener){m.removeEventListener(pc,O,false)}if(N){clearInterval(N)}}}
if(m.addEventListener){m.addEventListener(pc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(m.readyState)){J();O()}},50);n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});n&&n({moduleName:Q,sessionId:o,subSystem:R,evtGroup:_b,millis:(new Date).getTime(),type:T});m.write(qc)}
editprovider();