#
# clear text name
##############################################################################
oracle9i.name=Oracle 9i, 10g & 11g

#
# Alkacon OpenCms driver classes
##############################################################################
oracle9i.vfs.driver=org.opencms.db.oracle.CmsVfsDriver
oracle9i.user.driver=org.opencms.db.oracle.CmsUserDriver
oracle9i.project.driver=org.opencms.db.oracle.CmsProjectDriver
oracle9i.history.driver=org.opencms.db.oracle.CmsHistoryDriver
oracle9i.subscription.driver=org.opencms.db.oracle.CmsSubscriptionDriver

#
# validation query
##############################################################################
#oracle9i.testQuery=SELECT SYSDATE FROM DUAL;
#oracle9i.testQuery=SELECT * FROM CMS_OFFLINE_PROPERTYDEF WHERE PROPERTYDDEF_NAME = 'Title'
oracle9i.testQuery=SELECT 1 FROM DUAL

#
# JDBC driver
##############################################################################
oracle9i.driver=oracle.jdbc.driver.OracleDriver

#
# JDBC connect string
##############################################################################
oracle9i.constr=jdbc:oracle:thin:@localhost:1521:opencms
oracle9i.constr.params=

#
# database user
##############################################################################
oracle9i.user=system

#
# tablespaces used when creating an oracle user
##############################################################################
oracle9i.defaultTablespace=users
oracle9i.indexTablespace=users
oracle9i.temporaryTablespace=temp

#
# ranking used for setup select box
##############################################################################
oracle9i.ranking=270

#
# SQL manager class
##############################################################################
oracle9i.sqlmanager=org.opencms.db.oracle.CmsSqlManager

#
# Jdbc Drivers - Comma separated list of jars
##############################################################################
oracle9i.libs=ojdbc14-10.2.0.4.jar

#
# Separator - the separator for the connect String of the db
##############################################################################
oracle9i.separator=
