CREATE_CMS_STORAGE=\
CREATE TABLE CMS_STORAGE (\
    HASH VARCHAR(128) BINARY NOT NULL,\
    FILE_CONTENT LONGBLOB NOT NULL,\
    PRIMARY KEY(HASH)\
) CHARACTER SET utf8mb4

ADD_CMS_CONTENTS_STORAGE=ALTER TABLE CMS_CONTENTS ADD COLUMN STORAGE VARCHAR(32) BINARY
ADD_CMS_CONTENTS_HASH=ALTER TABLE CMS_CONTENTS ADD COLUMN HASH VARCHAR(128) BINARY
ADD_CMS_OFFLINE_CONTENTS_STORAGE=ALTER TABLE CMS_OFFLINE_CONTENTS ADD COLUMN STORAGE VARCHAR(32) BINARY
ADD_CMS_OFFLINE_CONTENTS_HASH=ALTER TABLE CMS_OFFLINE_CONTENTS ADD COLUMN HASH VARCHAR(128) BINARY

INDEX_CMS_CONTENTS_HASH=HASH_IDX
CREATE_CMS_CONTENTS_HASH_INDEX=CREATE INDEX HASH_IDX ON CMS_CONTENTS (HASH, STORAGE)
INDEX_CMS_CONTENTS_STORAGE=STORAGE_IDX
CREATE_CMS_CONTENTS_STORAGE_INDEX=CREATE INDEX STORAGE_IDX ON CMS_CONTENTS (STORAGE, HASH)
INDEX_CMS_OFFLINE_CONTENTS_HASH=HASH_IDX
CREATE_CMS_OFFLINE_CONTENTS_HASH_INDEX=CREATE INDEX HASH_IDX ON CMS_OFFLINE_CONTENTS (HASH, STORAGE)
INDEX_CMS_OFFLINE_CONTENTS_STORAGE=STORAGE_IDX
CREATE_CMS_OFFLINE_CONTENTS_STORAGE_INDEX=CREATE INDEX STORAGE_IDX ON CMS_OFFLINE_CONTENTS (STORAGE, HASH)
