#
# clear text name
##############################################################################
oracle12.name=Oracle 12.2, 18c, 19c & 21c

#
# Alkacon OpenCms driver classes
##############################################################################
oracle12.vfs.driver=org.opencms.db.oracle.CmsVfsDriver
oracle12.user.driver=org.opencms.db.oracle.CmsUserDriver
oracle12.project.driver=org.opencms.db.oracle.CmsProjectDriver
oracle12.history.driver=org.opencms.db.oracle.CmsHistoryDriver
oracle12.subscription.driver=org.opencms.db.oracle.CmsSubscriptionDriver

#
# validation query
##############################################################################
#oracle12.testQuery=SELECT SYSDATE FROM DUAL;
#oracle12.testQuery=SELECT * FROM CMS_OFFLINE_PROPERTYDEF WHERE PROPERTYDDEF_NAME = 'Title'
oracle12.testQuery=SELECT 1 FROM DUAL

#
# JDBC driver
##############################################################################
oracle12.driver=oracle.jdbc.driver.OracleDriver

#
# JDBC connect string
##############################################################################
oracle12.constr=jdbc:oracle:thin:@localhost:1521/opencms
oracle12.constr.params=

#
# database user
##############################################################################
oracle12.user=system

#
# tablespaces used when creating an oracle user
##############################################################################
oracle12.defaultTablespace=users
oracle12.indexTablespace=users
oracle12.temporaryTablespace=temp

#
# ranking used for setup select box
##############################################################################
oracle12.ranking=280

#
# SQL manager class
##############################################################################
oracle12.sqlmanager=org.opencms.db.oracle.CmsSqlManager

#
# Jdbc Drivers - Comma separated list of jars
##############################################################################
oracle12.libs=ojdbc11-21.21.0.0.0.jar

#
# Separator - the separator for the connect String of the db
##############################################################################
oracle12.separator=
