CREATE_CMS_STORAGE=\
CREATE TABLE CMS_STORAGE (\
    HASH VARCHAR2(128) NOT NULL,\
    FILE_CONTENT BLOB NOT NULL,\
    CONSTRAINT PK_STORAGE PRIMARY KEY(HASH) USING INDEX TABLESPACE ${indexTablespace}\
)\
STORAGE (INITIAL 256K NEXT 1M PCTINCREASE 0)\
    LOB(FILE_CONTENT) STORE AS (\
        CHUNK 32K PCTVERSION 20\
        CACHE\
)

ADD_CMS_CONTENTS_STORAGE=ALTER TABLE CMS_CONTENTS ADD (STORAGE VARCHAR2(32))
ADD_CMS_CONTENTS_HASH=ALTER TABLE CMS_CONTENTS ADD (HASH VARCHAR2(128))
ADD_CMS_OFFLINE_CONTENTS_STORAGE=ALTER TABLE CMS_OFFLINE_CONTENTS ADD (STORAGE VARCHAR2(32))
ADD_CMS_OFFLINE_CONTENTS_HASH=ALTER TABLE CMS_OFFLINE_CONTENTS ADD (HASH VARCHAR2(128))

INDEX_CMS_CONTENTS_HASH=CMS_CONTENTS_06_IDX
CREATE_CMS_CONTENTS_HASH_INDEX=CREATE INDEX CMS_CONTENTS_06_IDX ON CMS_CONTENTS (HASH, STORAGE) TABLESPACE ${indexTablespace}
INDEX_CMS_CONTENTS_STORAGE=CMS_CONTENTS_07_IDX
CREATE_CMS_CONTENTS_STORAGE_INDEX=CREATE INDEX CMS_CONTENTS_07_IDX ON CMS_CONTENTS (STORAGE, HASH) TABLESPACE ${indexTablespace}
INDEX_CMS_OFFLINE_CONTENTS_HASH=CMS_OFFLINE_CONTENTS_01_IDX
CREATE_CMS_OFFLINE_CONTENTS_HASH_INDEX=CREATE INDEX CMS_OFFLINE_CONTENTS_01_IDX ON CMS_OFFLINE_CONTENTS (HASH, STORAGE) TABLESPACE ${indexTablespace}
INDEX_CMS_OFFLINE_CONTENTS_STORAGE=CMS_OFFLINE_CONTENTS_02_IDX
CREATE_CMS_OFFLINE_CONTENTS_STORAGE_INDEX=CREATE INDEX CMS_OFFLINE_CONTENTS_02_IDX ON CMS_OFFLINE_CONTENTS (STORAGE, HASH) TABLESPACE ${indexTablespace}
