prompt 'package_usertypes';
@package_usertypes.sql;
prompt 'package_usererrors';
@package_usererrors.sql;
prompt 'package_body_usererrors';
@package_body_usererrors.sql;
prompt 'package_opencmsconstants';
@package_opencmsconstants;
prompt 'function_getnextid';
@function_getnextid.sql;
prompt 'package_opencmsgroup';
@package_opencmsgroup;
prompt 'package_opencmsaccess';
@package_opencmsaccess;
prompt 'package_opencmsproperty';
@package_opencmsproperty;
prompt 'package_opencmsresource';
@package_opencmsresource;
prompt 'package_opencmsproject';
@package_opencmsproject;
prompt 'package_body_opencmsgroup';
@package_body_opencmsgroup;
prompt 'package_body_opencmsaccess';
@package_body_opencmsaccess;
prompt 'package_body_opencmsproperty';
@package_body_opencmsproperty;
prompt 'package_body_opencmsresource';
@package_body_opencmsresource;
prompt 'package_body_opencmsproject';
@package_body_opencmsproject;