prompt 'package_usertypes';
@/oracleplsql/package_usertypes.sql;
prompt 'package_usererrors';
@/oracleplsql/package_usererrors.sql;
prompt 'package_body_usererrors';
@/oracleplsql/package_body_usererrors.sql;
prompt 'package_opencmsconstants';
@/oracleplsql/package_opencmsconstants;
prompt 'function_getnextid';
@/oracleplsql/function_getnextid.sql;
prompt 'package_opencmsgroup';
@/oracleplsql/package_opencmsgroup;
prompt 'package_opencmsaccess';
@/oracleplsql/package_opencmsaccess;
prompt 'package_opencmsproperty';
@/oracleplsql/package_opencmsproperty;
prompt 'package_opencmsresource';
@/oracleplsql/package_opencmsresource;
prompt 'package_opencmsproject';
@/oracleplsql/package_opencmsproject;
prompt 'package_body_opencmsgroup';
@/oracleplsql/package_body_opencmsgroup;
prompt 'package_body_opencmsaccess';
@/oracleplsql/package_body_opencmsaccess;
prompt 'package_body_opencmsproperty';
@/oracleplsql/package_body_opencmsproperty;
prompt 'package_body_opencmsresource';
@/oracleplsql/package_body_opencmsresource;
prompt 'package_body_opencmsproject';
@/oracleplsql/package_body_opencmsproject;