create table CMS_MODULE_ONLINE_MASTER   (MASTER_ID              VARCHAR(36) BINARY NOT NULL,
                                         SUB_ID                 INT NOT NULL,
                                         USER_ID                VARCHAR(36) BINARY NOT NULL,
                                         GROUP_ID               VARCHAR(36) BINARY NOT NULL,
                                         PROJECT_ID             INT NOT NULL,
                                         ACCESS_FLAGS           INT NOT NULL,
                                         STATE                  INT NOT NULL,
                                         LOCKED_BY              VARCHAR(36) BINARY NOT NULL,
                                         LASTMODIFIED_BY        VARCHAR(36) BINARY NOT NULL,
                                         DATE_CREATED           DATETIME NOT NULL,
                                         DATE_LASTMODIFIED      DATETIME NOT NULL,
                                         PUBLICATION_DATE       DATETIME,
                                         PURGE_DATE             DATETIME,
                                         FLAGS                  INT,
                                         FEED_ID                INT,
                                         FEED_REFERENCE         INT,
                                         FEED_FILENAME          VARCHAR(255),
                                         TITLE                  VARCHAR(255),
                                         DATA_BIG_0             TEXT,
                                         DATA_BIG_1             TEXT,
                                         DATA_BIG_2             TEXT,
                                         DATA_BIG_3             TEXT,
                                         DATA_BIG_4             TEXT,
                                         DATA_BIG_5             TEXT,
                                         DATA_BIG_6             TEXT,
                                         DATA_BIG_7             TEXT,
                                         DATA_BIG_8             TEXT,
                                         DATA_BIG_9             TEXT,
                                         DATA_MEDIUM_0          TEXT,
                                         DATA_MEDIUM_1          TEXT,
                                         DATA_MEDIUM_2          TEXT,
                                         DATA_MEDIUM_3          TEXT,
                                         DATA_MEDIUM_4          TEXT,
                                         DATA_MEDIUM_5          TEXT,
                                         DATA_MEDIUM_6          TEXT,
                                         DATA_MEDIUM_7          TEXT,
                                         DATA_MEDIUM_8          TEXT,
                                         DATA_MEDIUM_9          TEXT,
                                         DATA_SMALL_0           TEXT,
                                         DATA_SMALL_1           TEXT,
                                         DATA_SMALL_2           TEXT,
                                         DATA_SMALL_3           TEXT,
                                         DATA_SMALL_4           TEXT,
                                         DATA_SMALL_5           TEXT,
                                         DATA_SMALL_6           TEXT,
                                         DATA_SMALL_7           TEXT,
                                         DATA_SMALL_8           TEXT,
                                         DATA_SMALL_9           TEXT,
                                         DATA_SMALL_10          TEXT,
                                         DATA_SMALL_11          TEXT,
                                         DATA_SMALL_12          TEXT,
                                         DATA_SMALL_13          TEXT,
                                         DATA_SMALL_14          TEXT,
                                         DATA_SMALL_15          TEXT,
                                         DATA_SMALL_16          TEXT,
                                         DATA_SMALL_17          TEXT,
                                         DATA_SMALL_18          TEXT,
                                         DATA_SMALL_19          TEXT,
                                         DATA_SMALL_20          TEXT,
                                         DATA_SMALL_21          TEXT,
                                         DATA_SMALL_22          TEXT,
                                         DATA_SMALL_23          TEXT,
                                         DATA_SMALL_24          TEXT,
                                         DATA_SMALL_25          TEXT,
                                         DATA_SMALL_26          TEXT,
                                         DATA_SMALL_27          TEXT,
                                         DATA_SMALL_28          TEXT,
                                         DATA_SMALL_29          TEXT,
                                         DATA_SMALL_30          TEXT,
                                         DATA_SMALL_31          TEXT,
                                         DATA_SMALL_32          TEXT,
                                         DATA_SMALL_33          TEXT,
                                         DATA_SMALL_34          TEXT,
                                         DATA_SMALL_35          TEXT,
                                         DATA_SMALL_36          TEXT,
                                         DATA_SMALL_37          TEXT,
                                         DATA_SMALL_38          TEXT,
                                         DATA_SMALL_39          TEXT,
                                         DATA_INT_0             INT,
                                         DATA_INT_1             INT,
                                         DATA_INT_2             INT,
                                         DATA_INT_3             INT,
                                         DATA_INT_4             INT,
                                         DATA_INT_5             INT,
                                         DATA_INT_6             INT,
                                         DATA_INT_7             INT,
                                         DATA_INT_8             INT,
                                         DATA_INT_9             INT,
                                         DATA_REFERENCE_0       INT,
                                         DATA_REFERENCE_1       INT,
                                         DATA_REFERENCE_2       INT,
                                         DATA_REFERENCE_3       INT,
                                         DATA_REFERENCE_4       INT,
                                         DATA_REFERENCE_5       INT,
                                         DATA_REFERENCE_6       INT,
                                         DATA_REFERENCE_7       INT,
                                         DATA_REFERENCE_8       INT,
                                         DATA_REFERENCE_9       INT,
                                         DATA_DATE_0            DATETIME,
                                         DATA_DATE_1            DATETIME,
                                         DATA_DATE_2            DATETIME,
                                         DATA_DATE_3            DATETIME,
                                         DATA_DATE_4            DATETIME,
                                         index iSUB_ID (SUB_ID),
                                         primary key(MASTER_ID));
                                         
create table CMS_MODULE_ONLINE_CHANNEL_REL
                                        (MASTER_ID              VARCHAR(36) BINARY NOT NULL,
                                         CHANNEL_ID             VARCHAR(36) BINARY NOT NULL,
                                         CHANNEL_NAME			TEXT NOT NULL,
                                         primary key(CHANNEL_ID, MASTER_ID));

create table CMS_MODULE_ONLINE_MEDIA    (MEDIA_ID               INT NOT NULL,
                                         MASTER_ID              VARCHAR(36) BINARY NOT NULL,
                                         MEDIA_POSITION         INT NOT NULL,
                                         MEDIA_WIDTH            INT NOT NULL,
                                         MEDIA_HEIGHT           INT NOT NULL,
                                         MEDIA_SIZE             INT NOT NULL,
                                         MEDIA_MIMETYPE         VARCHAR(255),
                                         MEDIA_TYPE             INT NOT NULL,
                                         MEDIA_TITLE            VARCHAR(255),
                                         MEDIA_NAME             VARCHAR(255),
                                         MEDIA_DESCRIPTION      TEXT NOT NULL,
                                         MEDIA                  LONGBLOB NOT NULL,
                                         key(MASTER_ID),
                                         primary key(MEDIA_ID));
                                         

create table CMS_MODULE_MASTER          (MASTER_ID              VARCHAR(36) BINARY NOT NULL,
                                         SUB_ID                 INT NOT NULL,
                                         USER_ID                VARCHAR(36) BINARY NOT NULL,
                                         GROUP_ID               VARCHAR(36) BINARY NOT NULL,
                                         PROJECT_ID             INT NOT NULL,
                                         ACCESS_FLAGS           INT NOT NULL,
                                         STATE                  INT NOT NULL,
                                         LOCKED_BY              VARCHAR(36) BINARY NOT NULL,
                                         LASTMODIFIED_BY        VARCHAR(36) BINARY NOT NULL,
                                         DATE_CREATED           DATETIME NOT NULL,
                                         DATE_LASTMODIFIED      DATETIME NOT NULL,                                         
                                         PUBLICATION_DATE       DATETIME,
                                         PURGE_DATE             DATETIME,
                                         FLAGS                  INT NOT NULL,
                                         FEED_ID                INT NOT NULL,
                                         FEED_REFERENCE         INT NOT NULL,
                                         FEED_FILENAME          VARCHAR(255),
                                         TITLE                  VARCHAR(255),
                                         DATA_BIG_0             TEXT,
                                         DATA_BIG_1             TEXT,
                                         DATA_BIG_2             TEXT,
                                         DATA_BIG_3             TEXT,
                                         DATA_BIG_4             TEXT,
                                         DATA_BIG_5             TEXT,
                                         DATA_BIG_6             TEXT,
                                         DATA_BIG_7             TEXT,
                                         DATA_BIG_8             TEXT,
                                         DATA_BIG_9             TEXT,
                                         DATA_MEDIUM_0          TEXT,
                                         DATA_MEDIUM_1          TEXT,
                                         DATA_MEDIUM_2          TEXT,
                                         DATA_MEDIUM_3          TEXT,
                                         DATA_MEDIUM_4          TEXT,
                                         DATA_MEDIUM_5          TEXT,
                                         DATA_MEDIUM_6          TEXT,
                                         DATA_MEDIUM_7          TEXT,
                                         DATA_MEDIUM_8          TEXT,
                                         DATA_MEDIUM_9          TEXT,
                                         DATA_SMALL_0           TEXT,
                                         DATA_SMALL_1           TEXT,
                                         DATA_SMALL_2           TEXT,
                                         DATA_SMALL_3           TEXT,
                                         DATA_SMALL_4           TEXT,
                                         DATA_SMALL_5           TEXT,
                                         DATA_SMALL_6           TEXT,
                                         DATA_SMALL_7           TEXT,
                                         DATA_SMALL_8           TEXT,
                                         DATA_SMALL_9           TEXT,
                                         DATA_SMALL_10          TEXT,
                                         DATA_SMALL_11          TEXT,
                                         DATA_SMALL_12          TEXT,
                                         DATA_SMALL_13          TEXT,
                                         DATA_SMALL_14          TEXT,
                                         DATA_SMALL_15          TEXT,
                                         DATA_SMALL_16          TEXT,
                                         DATA_SMALL_17          TEXT,
                                         DATA_SMALL_18          TEXT,
                                         DATA_SMALL_19          TEXT,
                                         DATA_SMALL_20          TEXT,
                                         DATA_SMALL_21          TEXT,
                                         DATA_SMALL_22          TEXT,
                                         DATA_SMALL_23          TEXT,
                                         DATA_SMALL_24          TEXT,
                                         DATA_SMALL_25          TEXT,
                                         DATA_SMALL_26          TEXT,
                                         DATA_SMALL_27          TEXT,
                                         DATA_SMALL_28          TEXT,
                                         DATA_SMALL_29          TEXT,
                                         DATA_SMALL_30          TEXT,
                                         DATA_SMALL_31          TEXT,
                                         DATA_SMALL_32          TEXT,
                                         DATA_SMALL_33          TEXT,
                                         DATA_SMALL_34          TEXT,
                                         DATA_SMALL_35          TEXT,
                                         DATA_SMALL_36          TEXT,
                                         DATA_SMALL_37          TEXT,
                                         DATA_SMALL_38          TEXT,
                                         DATA_SMALL_39          TEXT,
                                         DATA_INT_0             INT,
                                         DATA_INT_1             INT,
                                         DATA_INT_2             INT,
                                         DATA_INT_3             INT,
                                         DATA_INT_4             INT,
                                         DATA_INT_5             INT,
                                         DATA_INT_6             INT,
                                         DATA_INT_7             INT,
                                         DATA_INT_8             INT,
                                         DATA_INT_9             INT,
                                         DATA_REFERENCE_0       INT,
                                         DATA_REFERENCE_1       INT,
                                         DATA_REFERENCE_2       INT,
                                         DATA_REFERENCE_3       INT,
                                         DATA_REFERENCE_4       INT,
                                         DATA_REFERENCE_5       INT,
                                         DATA_REFERENCE_6       INT,
                                         DATA_REFERENCE_7       INT,
                                         DATA_REFERENCE_8       INT,
                                         DATA_REFERENCE_9       INT,
                                         DATA_DATE_0            DATETIME,
                                         DATA_DATE_1            DATETIME,
                                         DATA_DATE_2            DATETIME,
                                         DATA_DATE_3            DATETIME,
                                         DATA_DATE_4            DATETIME,
                                         index iSUB_ID (SUB_ID),
                                         primary key(MASTER_ID));

create table CMS_MODULE_CHANNEL_REL
                                        (MASTER_ID              VARCHAR(36) BINARY NOT NULL,
                                         CHANNEL_ID             VARCHAR(36) BINARY NOT NULL,
                                         CHANNEL_NAME			TEXT NOT NULL,
                                         primary key(CHANNEL_ID, MASTER_ID));

create table CMS_MODULE_MEDIA           (MEDIA_ID               INT NOT NULL,
                                         MASTER_ID              VARCHAR(36) BINARY NOT NULL,
                                         MEDIA_POSITION         INT NOT NULL,
                                         MEDIA_WIDTH            INT NOT NULL,
                                         MEDIA_HEIGHT           INT NOT NULL,
                                         MEDIA_SIZE             INT NOT NULL,
                                         MEDIA_MIMETYPE         VARCHAR(255),
                                         MEDIA_TYPE             INT NOT NULL,
                                         MEDIA_TITLE            VARCHAR(255),
                                         MEDIA_NAME             VARCHAR(255),
                                         MEDIA_DESCRIPTION      TEXT NOT NULL,
                                         MEDIA                  LONGBLOB NOT NULL,
                                         key(MASTER_ID),
                                         primary key(MEDIA_ID));


create table CMS_MODULE_BACKUP_MASTER   (MASTER_ID              VARCHAR(36) BINARY NOT NULL,
                                         SUB_ID                 INT NOT NULL,
                                         USER_ID                VARCHAR(36) BINARY NOT NULL,
                                         GROUP_ID               VARCHAR(36) BINARY NOT NULL,
                                         PROJECT_ID             INT NOT NULL,
                                         ACCESS_FLAGS           INT NOT NULL,
                                         STATE                  INT NOT NULL,
                                         LOCKED_BY              VARCHAR(36) BINARY NOT NULL,
                                         LASTMODIFIED_BY        VARCHAR(36) BINARY NOT NULL,
                                         DATE_CREATED           DATETIME NOT NULL,
                                         DATE_LASTMODIFIED      DATETIME NOT NULL,
                                         PUBLICATION_DATE       DATETIME,
                                         PURGE_DATE             DATETIME,
                                         FLAGS                  INT NOT NULL,
                                         FEED_ID                INT NOT NULL,
                                         FEED_REFERENCE         INT NOT NULL,
                                         FEED_FILENAME          VARCHAR(255),
                                         TITLE                  VARCHAR(255),
                                         DATA_BIG_0             TEXT,
                                         DATA_BIG_1             TEXT,
                                         DATA_BIG_2             TEXT,
                                         DATA_BIG_3             TEXT,
                                         DATA_BIG_4             TEXT,
                                         DATA_BIG_5             TEXT,
                                         DATA_BIG_6             TEXT,
                                         DATA_BIG_7             TEXT,
                                         DATA_BIG_8             TEXT,
                                         DATA_BIG_9             TEXT,
                                         DATA_MEDIUM_0          TEXT,
                                         DATA_MEDIUM_1          TEXT,
                                         DATA_MEDIUM_2          TEXT,
                                         DATA_MEDIUM_3          TEXT,
                                         DATA_MEDIUM_4          TEXT,
                                         DATA_MEDIUM_5          TEXT,
                                         DATA_MEDIUM_6          TEXT,
                                         DATA_MEDIUM_7          TEXT,
                                         DATA_MEDIUM_8          TEXT,
                                         DATA_MEDIUM_9          TEXT,
                                         DATA_SMALL_0           TEXT,
                                         DATA_SMALL_1           TEXT,
                                         DATA_SMALL_2           TEXT,
                                         DATA_SMALL_3           TEXT,
                                         DATA_SMALL_4           TEXT,
                                         DATA_SMALL_5           TEXT,
                                         DATA_SMALL_6           TEXT,
                                         DATA_SMALL_7           TEXT,
                                         DATA_SMALL_8           TEXT,
                                         DATA_SMALL_9           TEXT,
                                         DATA_SMALL_10          TEXT,
                                         DATA_SMALL_11          TEXT,
                                         DATA_SMALL_12          TEXT,
                                         DATA_SMALL_13          TEXT,
                                         DATA_SMALL_14          TEXT,
                                         DATA_SMALL_15          TEXT,
                                         DATA_SMALL_16          TEXT,
                                         DATA_SMALL_17          TEXT,
                                         DATA_SMALL_18          TEXT,
                                         DATA_SMALL_19          TEXT,
                                         DATA_SMALL_20          TEXT,
                                         DATA_SMALL_21          TEXT,
                                         DATA_SMALL_22          TEXT,
                                         DATA_SMALL_23          TEXT,
                                         DATA_SMALL_24          TEXT,
                                         DATA_SMALL_25          TEXT,
                                         DATA_SMALL_26          TEXT,
                                         DATA_SMALL_27          TEXT,
                                         DATA_SMALL_28          TEXT,
                                         DATA_SMALL_29          TEXT,
                                         DATA_SMALL_30          TEXT,
                                         DATA_SMALL_31          TEXT,
                                         DATA_SMALL_32          TEXT,
                                         DATA_SMALL_33          TEXT,
                                         DATA_SMALL_34          TEXT,
                                         DATA_SMALL_35          TEXT,
                                         DATA_SMALL_36          TEXT,
                                         DATA_SMALL_37          TEXT,
                                         DATA_SMALL_38          TEXT,
                                         DATA_SMALL_39          TEXT,
                                         DATA_INT_0             INT,
                                         DATA_INT_1             INT,
                                         DATA_INT_2             INT,
                                         DATA_INT_3             INT,
                                         DATA_INT_4             INT,
                                         DATA_INT_5             INT,
                                         DATA_INT_6             INT,
                                         DATA_INT_7             INT,
                                         DATA_INT_8             INT,
                                         DATA_INT_9             INT,
                                         DATA_REFERENCE_0       INT,
                                         DATA_REFERENCE_1       INT,
                                         DATA_REFERENCE_2       INT,
                                         DATA_REFERENCE_3       INT,
                                         DATA_REFERENCE_4       INT,
                                         DATA_REFERENCE_5       INT,
                                         DATA_REFERENCE_6       INT,
                                         DATA_REFERENCE_7       INT,
                                         DATA_REFERENCE_8       INT,
                                         DATA_REFERENCE_9       INT,
                                         DATA_DATE_0            DATETIME,
                                         DATA_DATE_1            DATETIME,
                                         DATA_DATE_2            DATETIME,
                                         DATA_DATE_3            DATETIME,
                                         DATA_DATE_4            DATETIME,
                                         TAG_ID    		        INT NOT NULL,
                                         USER_NAME              VARCHAR(167),
                                         GROUP_NAME             VARCHAR(64),
                                         LASTMODIFIED_BY_NAME   VARCHAR(167),
                                         primary key(MASTER_ID, TAG_ID));

create table CMS_MODULE_BACKUP_MEDIA    (MEDIA_ID               INT NOT NULL,
                                         MASTER_ID              VARCHAR(36) BINARY NOT NULL,
                                         MEDIA_POSITION         INT NOT NULL,
                                         MEDIA_WIDTH            INT NOT NULL,
                                         MEDIA_HEIGHT           INT NOT NULL,
                                         MEDIA_SIZE             INT NOT NULL,
                                         MEDIA_MIMETYPE         VARCHAR(255),
                                         MEDIA_TYPE             INT NOT NULL,
                                         MEDIA_TITLE            VARCHAR(255),
                                         MEDIA_NAME             VARCHAR(255),
                                         MEDIA_DESCRIPTION      TEXT NOT NULL,
                                         MEDIA                  LONGBLOB NOT NULL,
                                         TAG_ID                 INT NOT NULL,
                                         key(MASTER_ID),
                                         primary key(MEDIA_ID, TAG_ID));
                                         
CREATE TABLE CMS_WEBUSERS (
	USER_ID VARCHAR(36) BINARY NOT NULL,
	USER_MEMBER_ID VARCHAR(255),
	USER_SALUTATION VARCHAR(255),
	USER_TITLE VARCHAR(255),
	USER_PWD VARCHAR(255),   
	USER_PWD_QUESTION VARCHAR(255),   
	USER_PWD_ANSWER VARCHAR(255),  
	USER_CITY VARCHAR(255),
	USER_POSTCODE VARCHAR(255),
	USER_STATE VARCHAR(255),
	USER_COUNTRY VARCHAR(255),
	USER_ADDRESS_TYPE INT,
	USER_BIRTHDAY DATETIME,
	USER_PHONE VARCHAR(255),
	USER_FAX VARCHAR(255),
	USER_MOBILE VARCHAR(255),
	USER_ACCEPT INT,   
	USER_RECOMMENDED_BY VARCHAR(255), 
	USER_PROFESSION VARCHAR(255),
	USER_COMPANY VARCHAR(255),
	USER_DEPARTMENT VARCHAR(255),
	USER_POSITION VARCHAR(255),   
	USER_ACCOUNT_NUMBER VARCHAR(255),
	USER_BANK_NUMBER VARCHAR(255),
	USER_BANK VARCHAR(255),
	USER_NEWSLETTER VARCHAR(255),   
	USER_EXTRAINFO_1 VARCHAR(255),
	USER_EXTRAINFO_2 VARCHAR(255),
	USER_EXTRAINFO_3 VARCHAR(255),
	USER_EXTRAINFO_4 VARCHAR(255),
	USER_EXTRAINFO_5 VARCHAR(255),
	USER_EXTRAINFO_6 VARCHAR(255),
	USER_EXTRAINFO_7 VARCHAR(255),
	USER_EXTRAINFO_8 VARCHAR(255),
	USER_EXTRAINFO_9 VARCHAR(255),
	USER_EXTRAINFO_10 VARCHAR(255),
	USER_EXTRAINFO_11 VARCHAR(255),
	USER_EXTRAINFO_12 VARCHAR(255),
	USER_EXTRAINFO_13 VARCHAR(255),
	USER_EXTRAINFO_14 VARCHAR(255),
	USER_EXTRAINFO_15 VARCHAR(255),
	USER_EXTRAINFO_16 VARCHAR(255),
	USER_EXTRAINFO_17 VARCHAR(255),
	USER_EXTRAINFO_18 VARCHAR(255),
	USER_EXTRAINFO_19 TEXT,
	USER_EXTRAINFO_20 TEXT,
	USER_PICTURE MEDIUMBLOB,
	USER_PICTURE_NAME VARCHAR(255),   
	USER_ATTACHMENT MEDIUMBLOB,
	USER_ATTACHMENT_NAME VARCHAR(255), 
	USER_CREATE_DATE DATETIME,
	USER_LASTCHANGE_BY VARCHAR(255),
	USER_LASTCHANGE_DATE DATETIME,
	LOCKSTATE VARCHAR(255),
	PRIMARY KEY (USER_ID)
);