CREATE TABLE CMS_USERS (
	USER_ID VARCHAR2(36) NOT NULL,
	USER_NAME VARCHAR2(64) NOT NULL,
	USER_PASSWORD VARCHAR2(32) NOT NULL,
	USER_DESCRIPTION VARCHAR2(255) NOT NULL,
	USER_FIRSTNAME VARCHAR2(50) NOT NULL,
	USER_LASTNAME VARCHAR2(50) NOT NULL,
	USER_EMAIL VARCHAR2(100) NOT NULL,
	USER_LASTLOGIN DATE NOT NULL,
	USER_FLAGS INT NOT NULL,
	USER_INFO LONG RAW,
	USER_ADDRESS VARCHAR2(100) NOT NULL,
	USER_TYPE INT NOT NULL,
	PRIMARY KEY(USER_ID),
	UNIQUE(USER_NAME)
);

CREATE TABLE CMS_GROUPS (
	GROUP_ID VARCHAR2(36) NOT NULL,
	PARENT_GROUP_ID VARCHAR2(36) NOT NULL,
	GROUP_NAME VARCHAR2(64) NOT NULL,
	GROUP_DESCRIPTION VARCHAR2(255) NOT NULL,
	GROUP_FLAGS INT NOT NULL,
	PRIMARY KEY(GROUP_ID),
	UNIQUE(GROUP_NAME)
);

CREATE INDEX IDX_CMS_GROUPS_01 
	ON CMS_GROUPS (PARENT_GROUP_ID);

CREATE TABLE CMS_GROUPUSERS (
	GROUP_ID VARCHAR2(36) NOT NULL,
	USER_ID VARCHAR2(36) NOT NULL,
	GROUPUSER_FLAGS INT NOT NULL
);

CREATE INDEX IDX_CMS_GROUPUSERS_01 
	ON CMS_GROUPUSERS (GROUP_ID);

CREATE INDEX IDX_CMS_GROUPUSERS_02 
	ON CMS_GROUPUSERS (USER_ID);
	
CREATE TABLE CMS_PROJECTS (
	PROJECT_ID INT NOT NULL,
	PROJECT_NAME VARCHAR2(64) NOT NULL,
	PROJECT_DESCRIPTION VARCHAR2(255) NOT NULL,
	PROJECT_FLAGS INT NOT NULL,
	PROJECT_TYPE INT NOT NULL,
	USER_ID VARCHAR2(36) NOT NULL,
	GROUP_ID VARCHAR2(36) NOT NULL,
	MANAGERGROUP_ID VARCHAR2(36) NOT NULL,
	TASK_ID INT NOT NULL,
	DATE_CREATED DATE NOT NULL,
	PRIMARY KEY (PROJECT_ID),
	UNIQUE(PROJECT_NAME,DATE_CREATED)
);
	
CREATE INDEX IDX_CMS_PROJECTS_01
	ON CMS_PROJECTS (PROJECT_FLAGS);
	
CREATE INDEX IDX_CMS_PROJECTS_02
	ON CMS_PROJECTS (GROUP_ID);
	
CREATE INDEX IDX_CMS_PROJECTS_03
	ON CMS_PROJECTS (MANAGERGROUP_ID);
	
CREATE INDEX IDX_CMS_PROJECTS_04
	ON CMS_PROJECTS (USER_ID);
	
CREATE INDEX IDX_CMS_PROJECTS_05
	ON CMS_PROJECTS (TASK_ID);	

CREATE TABLE CMS_BACKUP_PROJECTS (
	PROJECT_ID INT NOT NULL,
	PROJECT_NAME VARCHAR2(64) NOT NULL,
	PROJECT_DESCRIPTION VARCHAR2(255) NOT NULL,
	PROJECT_TYPE INT NOT NULL,
	USER_ID VARCHAR2(36) NOT NULL,
	GROUP_ID VARCHAR2(36) NOT NULL,
	MANAGERGROUP_ID VARCHAR2(36) NOT NULL,
	TASK_ID INT NOT NULL,
	DATE_CREATED DATE NOT NULL,
	PUBLISH_TAG INT NOT NULL,
	PROJECT_PUBLISHDATE DATE,
	PROJECT_PUBLISHED_BY VARCHAR2(36) NOT NULL,
	PROJECT_PUBLISHED_BY_NAME VARCHAR2(167),
	USER_NAME VARCHAR2(167),
	GROUP_NAME VARCHAR2(64),
	MANAGERGROUP_NAME VARCHAR2(64),
	PRIMARY KEY(VERSION_ID)
);

CREATE TABLE CMS_PROJECTRESOURCES (
	PROJECT_ID INT NOT NULL,
	RESOURCE_PATH VARCHAR2(1024) NOT NULL,
	PRIMARY KEY(PROJECT_ID, RESOURCE_PATH)
);

CREATE INDEX IDX_CMS_PROJECTRESOURCES_01
	ON CMS_PROJECTRESOURCES (RESOURCE_PATH);

CREATE TABLE CMS_BACKUP_PROJECTRESOURCES (
	PUBLISH_TAG INT NOT NULL,
	PROJECT_ID INT NOT NULL,
	RESOURCE_PATH VARCHAR2(1024) NOT NULL,
	PRIMARY KEY (PUBLISH_TAG, PROJECT_ID, RESOURCE_PATH)
);

CREATE TABLE CMS_OFFLINE_PROPERTYDEF (
	PROPERTYDEF_ID VARCHAR2(36) NOT NULL,
	PROPERTYDEF_NAME VARCHAR2(64) NOT NULL,
	PRIMARY KEY(PROPERTYDEF_ID),
	UNIQUE(PROPERTYDEF_NAME)
);	

CREATE TABLE CMS_ONLINE_PROPERTYDEF (
	PROPERTYDEF_ID VARCHAR2(36) NOT NULL,
	PROPERTYDEF_NAME VARCHAR2(64) NOT NULL,
	PRIMARY KEY(PROPERTYDEF_ID),
	UNIQUE(PROPERTYDEF_NAME)
);

CREATE TABLE CMS_BACKUP_PROPERTYDEF (
	PROPERTYDEF_ID VARCHAR2(36) NOT NULL,
	PROPERTYDEF_NAME VARCHAR2(64) NOT NULL,
	PRIMARY KEY(PROPERTYDEF_ID),
	UNIQUE(PROPERTYDEF_NAME)
);

CREATE TABLE CMS_OFFLINE_PROPERTIES (
	PROPERTY_ID VARCHAR2(36) NOT NULL,
	PROPERTYDEF_ID VARCHAR2(36) NOT NULL,
	PROPERTY_MAPPING_ID VARCHAR2(36) NOT NULL,
	PROPERTY_MAPPING_TYPE INT NOT NULL,	
	PROPERTY_VALUE VARCHAR2(255) NOT NULL,
	PRIMARY KEY(PROPERTY_ID)
);

CREATE INDEX IDX_CMS_OFFLINE_PROPERTIES_01
	ON CMS_OFFLINE_PROPERTIES (PROPERTYDEF_ID);
	
CREATE INDEX IDX_CMS_OFFLINE_PROPERTIES_02
	ON CMS_OFFLINE_PROPERTIES (PROPERTY_MAPPING_ID);
	
CREATE INDEX IDX_CMS_OFFLINE_PROPERTIES_03
	ON CMS_OFFLINE_PROPERTIES (PROPERTYDEF_ID, PROPERTY_MAPPING_ID);	

CREATE TABLE CMS_ONLINE_PROPERTIES (
	PROPERTY_ID VARCHAR2(36) NOT NULL,
	PROPERTYDEF_ID VARCHAR2(36) NOT NULL,
	PROPERTY_MAPPING_ID VARCHAR2(36) NOT NULL,
	PROPERTY_MAPPING_TYPE INT NOT NULL,	
	PROPERTY_VALUE VARCHAR2(255) NOT NULL,
	PRIMARY KEY(PROPERTY_ID)
);

CREATE INDEX IDX_CMS_ONLINE_PROPERTIES_01
	ON CMS_ONLINE_PROPERTIES (PROPERTYDEF_ID);
	
CREATE INDEX IDX_CMS_ONLINE_PROPERTIES_02
	ON CMS_ONLINE_PROPERTIES (PROPERTY_MAPPING_ID);
	
CREATE INDEX IDX_CMS_ONLINE_PROPERTIES_03
	ON CMS_ONLINE_PROPERTIES (PROPERTYDEF_ID, PROPERTY_MAPPING_ID);

CREATE TABLE CMS_BACKUP_PROPERTIES (
	PROPERTY_ID VARCHAR2(36) NOT NULL,
	PROPERTYDEF_ID VARCHAR2(36) NOT NULL,
	PROPERTY_MAPPING_ID VARCHAR2(36) NOT NULL,
	PROPERTY_MAPPING_TYPE INT NOT NULL,		
	PROPERTY_VALUE VARCHAR2(255) NOT NULL,
	VERSION_ID INT,
	PRIMARY KEY(PROPERTY_ID)
);

CREATE INDEX IDX_CMS_BACKUP_PROPERTIES_01
	ON CMS_BACKUP_PROPERTIES (PROPERTYDEF_ID);
	
CREATE INDEX IDX_CMS_BACKUP_PROPERTIES_02
	ON CMS_BACKUP_PROPERTIES (PROPERTY_MAPPING_ID);
	
CREATE INDEX IDX_CMS_BACKUP_PROPERTIES_03
	ON CMS_BACKUP_PROPERTIES (PROPERTYDEF_ID, PROPERTY_MAPPING_ID);

CREATE TABLE CMS_SYSTEMID (
	TABLE_KEY VARCHAR2(255) NOT NULL,
	ID INT NOT NULL,
	PRIMARY KEY (TABLE_KEY)
);

CREATE TABLE CMS_TASK (
	AUTOFINISH INT,
	ENDTIME DATE,
	ESCALATIONTYPEREF INT,
	ID INT NOT NULL,
	INITIATORUSERREF VARCHAR2(36),
	MILESTONEREF INT,
	NAME VARCHAR(254),
	ORIGINALUSERREF VARCHAR2(36),
	AGENTUSERREF VARCHAR2(36),
	PARENT INT,
	PERCENTAGE VARCHAR(50),
	PERMISSION VARCHAR(50),
	PRIORITYREF INT DEFAULT '2',
	ROLEREF VARCHAR2(36),
	ROOT INT,
	STARTTIME DATE,
	STATE INT,
	TASKTYPE INT,
	TIMEOUT DATE,
	WAKEUPTIME DATE,
	HTMLLINK VARCHAR(254),
	ESTIMATETIME INT DEFAULT '86400',
	PRIMARY KEY(ID)
);

CREATE TABLE CMS_TASKTYPE (
	AUTOFINISH INT,
	ESCALATIONTYPEREF INT,
	HTMLLINK VARCHAR(254),
	ID INT NOT NULL,
	NAME VARCHAR(50),
	PERMISSION VARCHAR(50),
	PRIORITYREF INT,
	ROLEREF VARCHAR2(36),
	PRIMARY KEY(ID)
);

CREATE TABLE CMS_TASKLOG (
	COMENT LONG,
	EXTERNALUSERNAME VARCHAR(254),
	ID INT NOT NULL,
	STARTTIME DATE,
	TASKREF INT,
	USERREF INT,
	TYPE INT DEFAULT '0',
	PRIMARY KEY(ID)
);

CREATE TABLE CMS_TASKPAR (
	ID INT NOT NULL,
	PARNAME VARCHAR(50),
	PARVALUE VARCHAR(50),
	REF INT,
	PRIMARY KEY(ID)
);

CREATE TABLE CMS_ONLINE_ACCESSCONTROL (
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	PRINCIPAL_ID VARCHAR2(36) NOT NULL,
	ACCESS_ALLOWED INT,
	ACCESS_DENIED INT,
	ACCESS_FLAGS INT,
	PRIMARY KEY(RESOURCE_ID, PRINCIPAL_ID)
);

CREATE TABLE CMS_OFFLINE_ACCESSCONTROL (
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	PRINCIPAL_ID VARCHAR2(36) NOT NULL,
	ACCESS_ALLOWED INT,
	ACCESS_DENIED INT,
	ACCESS_FLAGS INT,
	PRIMARY KEY(RESOURCE_ID, PRINCIPAL_ID)
);

CREATE TABLE CMS_PUBLISH_HISTORY (
	HISTORY_ID VARCHAR(36) NOT NULL,
	PUBLISH_TAG INT NOT NULL,
	STRUCTURE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_PATH VARCHAR2(1024) NOT NULL,
	RESOURCE_STATE INT NOT NULL,
	RESOURCE_TYPE INT NOT NULL,
	SIBLING_COUNT INT NOT NULL,
	CONSTRAINT PK_PUBLISH_HISTORY PRIMARY KEY(HISTORY_ID,PUBLISH_TAG,STRUCTURE_ID,RESOURCE_ID)
);

CREATE TABLE CMS_STATICEXPORT_LINKS (
	LINK_ID VARCHAR(36) NOT NULL,
	LINK_RFS_PATH VARCHAR(1024) NOT NULL,
	LINK_TYPE INT NOT NULL,
	LINK_PARAMETER VARCHAR(1024),
	LINK_TIMESTAMP NUMBER NOT NULL,
	PRIMARY KEY(LINK_ID)	
);

CREATE TABLE CMS_OFFLINE_STRUCTURE (
	STRUCTURE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	PARENT_ID VARCHAR2(36) NOT NULL,
	RESOURCE_PATH VARCHAR2(1024) NOT NULL,
	STRUCTURE_STATE INT NOT NULL,
	DATE_RELEASED DATE NOT NULL,
	DATE_EXPIRED DATE NOT NULL,
	PRIMARY KEY(STRUCTURE_ID)
);

CREATE INDEX IDX_CMS_OFFLINE_STRUCTURE_01
	ON CMS_OFFLINE_STRUCTURE (STRUCTURE_ID, RESOURCE_PATH);
	
CREATE INDEX IDX_CMS_OFFLINE_STRUCTURE_02
	ON CMS_OFFLINE_STRUCTURE (RESOURCE_PATH, RESOURCE_ID);
	
CREATE INDEX IDX_CMS_OFFLINE_STRUCTURE_03
	ON CMS_OFFLINE_STRUCTURE (STRUCTURE_ID, RESOURCE_ID);
	
CREATE INDEX IDX_CMS_OFFLINE_STRUCTURE_04
	ON CMS_OFFLINE_STRUCTURE (STRUCTURE_STATE);
	
CREATE INDEX IDX_CMS_OFFLINE_STRUCTURE_05
	ON CMS_OFFLINE_STRUCTURE (PARENT_ID);
	
CREATE INDEX IDX_CMS_OFFLINE_STRUCTURE_06
	ON CMS_OFFLINE_STRUCTURE (RESOURCE_ID);
	
CREATE INDEX IDX_CMS_OFFLINE_STRUCTURE_07
	ON CMS_OFFLINE_STRUCTURE (RESOURCE_PATH);	

CREATE TABLE CMS_ONLINE_STRUCTURE (
	STRUCTURE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	PARENT_ID VARCHAR2(36) NOT NULL,
	RESOURCE_PATH VARCHAR2(1024) NOT NULL,
	STRUCTURE_STATE INT NOT NULL,	
	DATE_RELEASED DATE NOT NULL,
	DATE_EXPIRED DATE NOT NULL,
	PRIMARY KEY(STRUCTURE_ID)
);

CREATE INDEX IDX_CMS_ONLINE_STRUCTURE_01
	ON CMS_ONLINE_STRUCTURE (STRUCTURE_ID, RESOURCE_PATH);
	
CREATE INDEX IDX_CMS_ONLINE_STRUCTURE_02
	ON CMS_ONLINE_STRUCTURE (RESOURCE_PATH, RESOURCE_ID);
	
CREATE INDEX IDX_CMS_ONLINE_STRUCTURE_03
	ON CMS_ONLINE_STRUCTURE (STRUCTURE_ID, RESOURCE_ID);
	
CREATE INDEX IDX_CMS_ONLINE_STRUCTURE_04
	ON CMS_ONLINE_STRUCTURE (STRUCTURE_STATE);
	
CREATE INDEX IDX_CMS_ONLINE_STRUCTURE_05
	ON CMS_ONLINE_STRUCTURE (PARENT_ID);
	
CREATE INDEX IDX_CMS_ONLINE_STRUCTURE_06
	ON CMS_ONLINE_STRUCTURE (RESOURCE_ID);
	
CREATE INDEX IDX_CMS_ONLINE_STRUCTURE_07
	ON CMS_ONLINE_STRUCTURE (RESOURCE_PATH);

CREATE TABLE CMS_BACKUP_STRUCTURE (
	BACKUP_ID VARCHAR2(36) NOT NULL,
	VERSION_ID INT NOT NULL,
	STRUCTURE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_PATH VARCHAR2(1024) NOT NULL,
	STRUCTURE_STATE INT NOT NULL,
	DATE_RELEASED DATE NOT NULL,
	DATE_EXPIRED DATE NOT NULL,
	PRIMARY KEY(BACKUP_ID)
);   

CREATE INDEX IDX_CMS_BACKUP_STRUCTURE_01
	ON CMS_BACKUP_STRUCTURE (STRUCTURE_ID, RESOURCE_PATH);
	
CREATE INDEX IDX_CMS_BACKUP_STRUCTURE_02
	ON CMS_BACKUP_STRUCTURE (RESOURCE_PATH, RESOURCE_ID);
	
CREATE INDEX IDX_CMS_BACKUPE_STRUCTURE_03
	ON CMS_BACKUP_STRUCTURE (STRUCTURE_ID, RESOURCE_ID);
	
CREATE INDEX IDX_CMS_BACKUP_STRUCTURE_04
	ON CMS_BACKUP_STRUCTURE (STRUCTURE_STATE);
	
CREATE INDEX IDX_CMS_BACKUP_STRUCTURE_05
	ON CMS_BACKUP_STRUCTURE (RESOURCE_ID);
	
CREATE INDEX IDX_CMS_BACKUP_STRUCTURE_07
	ON CMS_BACKUP_STRUCTURE (RESOURCE_PATH);

CREATE TABLE CMS_OFFLINE_RESOURCES (
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_TYPE INT NOT NULL,
	RESOURCE_FLAGS INT NOT NULL,
	RESOURCE_STATE INT NOT NULL,
	RESOURCE_SIZE INT NOT NULL,
	SIBLING_COUNT INT NOT NULL,	
	DATE_CREATED DATE NOT NULL,
	DATE_LASTMODIFIED DATE NOT NULL,
	USER_CREATED VARCHAR2(36) NOT NULL,
	USER_LASTMODIFIED VARCHAR2(36) NOT NULL,
	PROJECT_LASTMODIFIED INT NOT NULL,
	PRIMARY KEY(RESOURCE_ID)
);

CREATE INDEX IDX_CMS_OFFLINE_RESOURCES_01
	ON CMS_OFFLINE_RESOURCES (PROJECT_LASTMODIFIED);

CREATE INDEX IDX_CMS_OFFLINE_RESOURCES_02
	ON CMS_OFFLINE_RESOURCES (PROJECT_LASTMODIFIED, RESOURCE_SIZE);

CREATE INDEX IDX_CMS_OFFLINE_RESOURCES_03
	ON CMS_OFFLINE_RESOURCES (RESOURCE_SIZE);
	
CREATE INDEX IDX_CMS_OFFLINE_RESOURCES_04
	ON CMS_OFFLINE_RESOURCES (DATE_LASTMODIFIED);
	
CREATE INDEX IDX_CMS_OFFLINE_RESOURCES_05
	ON CMS_OFFLINE_RESOURCES (RESOURCE_TYPE);	

CREATE TABLE CMS_ONLINE_RESOURCES (
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_TYPE INT NOT NULL,
	RESOURCE_FLAGS INT NOT NULL,
	RESOURCE_STATE INT NOT NULL,
	RESOURCE_SIZE INT NOT NULL,
	SIBLING_COUNT INT NOT NULL,	
	DATE_CREATED DATE NOT NULL,
	DATE_LASTMODIFIED DATE NOT NULL,
	USER_CREATED VARCHAR2(36) NOT NULL,
	USER_LASTMODIFIED VARCHAR2(36) NOT NULL,
	PROJECT_LASTMODIFIED INT NOT NULL,
	PRIMARY KEY(RESOURCE_ID)
);

CREATE INDEX IDX_CMS_ONLINE_RESOURCES_01
	ON CMS_ONLINE_RESOURCES (PROJECT_LASTMODIFIED);

CREATE INDEX IDX_CMS_ONLINE_RESOURCES_02
	ON CMS_ONLINE_RESOURCES (PROJECT_LASTMODIFIED, RESOURCE_SIZE);

CREATE INDEX IDX_CMS_ONLINE_RESOURCES_03
	ON CMS_ONLINE_RESOURCES (RESOURCE_SIZE);
	
CREATE INDEX IDX_CMS_ONLINE_RESOURCES_04
	ON CMS_ONLINE_RESOURCES (DATE_LASTMODIFIED);
	
CREATE INDEX IDX_CMS_ONLINE_RESOURCES_05
	ON CMS_ONLINE_RESOURCES (RESOURCE_TYPE);

CREATE TABLE CMS_BACKUP_RESOURCES (
	BACKUP_ID VARCHAR2(36) NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_TYPE INT NOT NULL,
	RESOURCE_FLAGS INT NOT NULL,
	RESOURCE_STATE INT NOT NULL,
	RESOURCE_SIZE INT NOT NULL,
	SIBLING_COUNT INT NOT NULL,	
	DATE_CREATED DATE NOT NULL,
	DATE_LASTMODIFIED DATE NOT NULL,
	USER_CREATED VARCHAR2(36) NOT NULL,
	USER_LASTMODIFIED VARCHAR2(36) NOT NULL,
	PROJECT_LASTMODIFIED INT NOT NULL,
	PUBLISH_TAG INT NOT NULL,
	VERSION_ID INT NOT NULL,
	USER_CREATED_NAME VARCHAR2(64) NOT NULL,
	USER_LASTMODIFIED_NAME VARCHAR2(64) NOT NULL,
	PRIMARY KEY(BACKUP_ID),
	UNIQUE(VERSION_ID,RESOURCE_ID)
);

CREATE INDEX IDX_CMS_BACKUP_RESOURCES_01
	ON CMS_BACKUP_RESOURCES (PROJECT_LASTMODIFIED);
	
CREATE INDEX IDX_CMS_BACKUP_RESOURCES_02
	ON CMS_BACKUP_RESOURCES (PROJECT_LASTMODIFIED, RESOURCE_SIZE);
	
CREATE INDEX IDX_CMS_BACKUP_RESOURCES_03
	ON CMS_BACKUP_RESOURCES (RESOURCE_SIZE);
	
CREATE INDEX IDX_CMS_BACKUP_RESOURCES_04
	ON CMS_BACKUP_RESOURCES (DATE_LASTMODIFIED);
	
CREATE INDEX IDX_CMS_BACKUP_RESOURCES_05
	ON CMS_BACKUP_RESOURCES (RESOURCE_TYPE);	

CREATE TABLE CMS_OFFLINE_CONTENTS (
	CONTENT_ID VARCHAR2(36) NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	FILE_CONTENT BLOB NOT NULL,
	PRIMARY KEY (CONTENT_ID)
);

CREATE INDEX IDX_CMS_OFFLINE_CONTENTS_01
	ON CMS_OFFLINE_CONTENTS (RESOURCE_ID);

CREATE TABLE CMS_ONLINE_CONTENTS (
	CONTENT_ID VARCHAR2(36) NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	FILE_CONTENT BLOB NOT NULL,
	PRIMARY KEY (CONTENT_ID)
);

CREATE INDEX IDX_CMS_ONLINE_CONTENTS_01
	ON CMS_ONLINE_CONTENTS (RESOURCE_ID);

CREATE TABLE CMS_BACKUP_CONTENTS (
	BACKUP_ID VARCHAR2(36) NOT NULL,
	CONTENT_ID VARCHAR2(36) NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	FILE_CONTENT BLOB NOT NULL,
	VERSION_ID INT,
	PRIMARY KEY (BACKUP_ID)
);

CREATE INDEX IDX_CMS_BACKUP_CONTENTS_01
	ON CMS_BACKUP_CONTENTS (RESOURCE_ID);
