# Overwrite all VFS driver queries related to the CMS_CONTENTS and CMS_OFFLINE_CONTENTS
# tables, i.e., make sure to always read and write the additional STORAGE and HASH columns

C_OFFLINE_CONTENTS_WRITE=\
INSERT INTO CMS_OFFLINE_CONTENTS (\
    RESOURCE_ID,\
    FILE_CONTENT, \
    STORAGE, \
    HASH) \
VALUES \
    (?,?,?,?)

C_ONLINE_CONTENTS_WRITE=\
INSERT INTO CMS_CONTENTS (\
    RESOURCE_ID,\
    FILE_CONTENT,\
    STORAGE,\
    HASH,\
    PUBLISH_TAG_FROM,\
    PUBLISH_TAG_TO,\
    ONLINE_FLAG) \
VALUES \
    (?,?,?,?,?,?,?)

C_HISTORY_READ_CONTENT=\
SELECT \
    CMS_CONTENTS.FILE_CONTENT, CMS_CONTENTS.STORAGE, CMS_CONTENTS.HASH \
FROM \
    CMS_CONTENTS \
WHERE \
    CMS_CONTENTS.RESOURCE_ID=? \
    AND CMS_CONTENTS.PUBLISH_TAG_TO>=? \
    AND CMS_CONTENTS.PUBLISH_TAG_FROM<=?

C_CONTENT_HISTORY_STORAGE_READ=\
SELECT DISTINCT \
    CMS_CONTENTS.STORAGE, CMS_CONTENTS.HASH \
FROM \
    CMS_CONTENTS \
WHERE \
    CMS_CONTENTS.ONLINE_FLAG = 0 \
    AND CMS_CONTENTS.RESOURCE_ID=? \
    AND CMS_CONTENTS.PUBLISH_TAG_TO<? \
    AND CMS_CONTENTS.STORAGE IS NOT NULL \
    AND CMS_CONTENTS.HASH IS NOT NULL

C_OFFLINE_CONTENTS_UPDATE=\
UPDATE \
    CMS_OFFLINE_CONTENTS \
SET \
    FILE_CONTENT=?, STORAGE=?, HASH=? \
WHERE \
    CMS_OFFLINE_CONTENTS.RESOURCE_ID=?

C_ONLINE_FILES_CONTENT=\
SELECT \
    CMS_CONTENTS.FILE_CONTENT, CMS_CONTENTS.STORAGE, CMS_CONTENTS.HASH \
FROM \
    CMS_CONTENTS,\
    CMS_ONLINE_RESOURCES \
WHERE \
    CMS_ONLINE_RESOURCES.RESOURCE_ID=? \
    AND ${C_JOIN_RESOURCE_ONLINE_FILE}

C_OFFLINE_FILES_CONTENT=\
SELECT \
    CMS_OFFLINE_CONTENTS.FILE_CONTENT, CMS_OFFLINE_CONTENTS.STORAGE, CMS_OFFLINE_CONTENTS.HASH \
FROM \
    CMS_OFFLINE_CONTENTS \
WHERE \
    CMS_OFFLINE_CONTENTS.RESOURCE_ID=?

# Queries relevant for the storage driver only

C_STORAGE_CONTENT_INUSE=\
    SELECT 1 FROM CMS_OFFLINE_CONTENTS WHERE HASH=? AND STORAGE=? \
    UNION ALL \
    SELECT 1 FROM CMS_CONTENTS WHERE HASH=? AND STORAGE=?

C_STORAGE_EXISTS=\
    SELECT 1 FROM CMS_STORAGE WHERE HASH=?

C_STORAGE_FILE_CONTENT=\
    SELECT FILE_CONTENT FROM CMS_STORAGE WHERE HASH=?

C_STORAGE_DELETE=\
    DELETE FROM CMS_STORAGE WHERE HASH=?

C_STORAGE_WRITE=\
    INSERT INTO CMS_STORAGE (\
        HASH, \
        FILE_CONTENT) \
    VALUES \
        (?,?)
