CREATE TABLE CMS_SYSTEMPROPERTIES (   
	SYSTEMPROPERTY_ID INT NOT NULL,
	SYSTEMPROPERTY_NAME VARCHAR2(40) NOT NULL,
	SYSTEMPROPERTY_VALUE BLOB,
	CONSTRAINT PK_SYSTEMPROPERTIES PRIMARY KEY(SYSTEMPROPERTY_ID) USING INDEX TABLESPACE ${indexTablespace} ,
	CONSTRAINT UK_SYSTEMPROPERTIES UNIQUE(SYSTEMPROPERTY_NAME) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_USERS ( 
	USER_ID VARCHAR2(36) NOT NULL,
	USER_NAME VARCHAR2(64) NOT NULL,
	USER_PASSWORD VARCHAR2(32) NOT NULL,
	USER_RECOVERY_PASSWORD VARCHAR2(32) NOT NULL,
	USER_DESCRIPTION VARCHAR2(255) NOT NULL,
	USER_FIRSTNAME VARCHAR2(50) NOT NULL,
	USER_LASTNAME VARCHAR2(50) NOT NULL,
	USER_EMAIL VARCHAR2(100) NOT NULL,
	USER_LASTLOGIN DATE NOT NULL,
	USER_LASTUSED DATE NOT NULL,
	USER_FLAGS INT NOT NULL,
	USER_INFO BLOB,
	USER_DEFAULT_GROUP_ID VARCHAR2(36) NOT NULL,
	USER_ADDRESS VARCHAR2(100) NOT NULL ,
	USER_SECTION VARCHAR2(50) NOT NULL ,
	USER_TYPE INT NOT NULL,
	CONSTRAINT PK_USERS PRIMARY KEY(USER_ID)USING INDEX TABLESPACE ${indexTablespace} ,
	CONSTRAINT UK_USERS UNIQUE(USER_NAME) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_PROJECTS ( 
	PROJECT_ID INT NOT NULL,
	USER_ID VARCHAR2(36) NOT NULL,
	GROUP_ID VARCHAR2(36) NOT NULL,
	MANAGERGROUP_ID VARCHAR2(36) NOT NULL,
	TASK_ID INT NOT NULL,
	PROJECT_NAME VARCHAR2(64) NOT NULL,
	PROJECT_DESCRIPTION VARCHAR2(255) NOT NULL,
	PROJECT_FLAGS INT NOT NULL,
	PROJECT_CREATEDATE DATE NOT NULL,
	PROJECT_TYPE INT NOT NULL,
	CONSTRAINT PK_PROJECTS PRIMARY KEY(PROJECT_ID) USING INDEX TABLESPACE ${indexTablespace} ,
	CONSTRAINT UK_PROJECTS UNIQUE(PROJECT_NAME,PROJECT_CREATEDATE) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_BACKUP_PROJECTS (
	TAG_ID INT NOT NULL,
	PROJECT_ID INT NOT NULL,
	PROJECT_NAME VARCHAR2(64) NOT NULL,
	PROJECT_PUBLISHDATE DATE,
	PROJECT_PUBLISHED_BY VARCHAR2(36) NOT NULL,
	PROJECT_PUBLISHED_BY_NAME VARCHAR2(167),
	USER_ID VARCHAR2(36) NOT NULL,
	USER_NAME VARCHAR2(167),
	GROUP_ID VARCHAR2(36) NOT NULL,
	GROUP_NAME VARCHAR2(64),
	MANAGERGROUP_ID VARCHAR2(36) NOT NULL,
	MANAGERGROUP_NAME VARCHAR2(64),
	PROJECT_DESCRIPTION VARCHAR2(255) NOT NULL,
	PROJECT_CREATEDATE DATE NOT NULL,
	PROJECT_TYPE INT NOT NULL,
	TASK_ID INT NOT NULL,
	CONSTRAINT PK_BACKUP_PROJECTS PRIMARY KEY(TAG_ID) USING INDEX TABLESPACE ${indexTablespace}
);
 
CREATE TABLE CMS_PROJECTRESOURCES (
	PROJECT_ID NUMBER NOT NULL,
	RESOURCE_NAME VARCHAR2(248) NOT NULL,
	CONSTRAINT PK_PROJECTRESOURCES PRIMARY KEY(PROJECT_ID, RESOURCE_NAME) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_BACKUP_PROJECTRESOURCES (
	TAG_ID INT NOT NULL,
	PROJECT_ID INT NOT NULL,
	RESOURCE_NAME VARCHAR2(248) NOT NULL,
	CONSTRAINT PK_BACKUP_PROJECTRESOURCES PRIMARY KEY(TAG_ID, PROJECT_ID, RESOURCE_NAME) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_OFFLINE_PROPERTYDEF ( 
	PROPERTYDEF_ID INT NOT NULL,
	PROPERTYDEF_NAME VARCHAR2(128) NOT NULL,
	RESOURCE_TYPE INT NOT NULL,
	CONSTRAINT PK_OFFLINE_PROPERTYDEF PRIMARY KEY(PROPERTYDEF_ID) USING INDEX TABLESPACE ${indexTablespace} ,
	CONSTRAINT UK_OFFLINE_PROPERTYDEF UNIQUE(PROPERTYDEF_NAME, RESOURCE_TYPE) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_ONLINE_PROPERTYDEF ( 
	PROPERTYDEF_ID INT NOT NULL,
	PROPERTYDEF_NAME VARCHAR2(128) NOT NULL,
	RESOURCE_TYPE INT NOT NULL,
	CONSTRAINT PK_ONLINE_PROPERTYDEF PRIMARY KEY(PROPERTYDEF_ID) USING INDEX TABLESPACE ${indexTablespace} ,
	CONSTRAINT UK_ONLINE_PROPERTYDEF UNIQUE(PROPERTYDEF_NAME, RESOURCE_TYPE) USING INDEX TABLESPACE ${indexTablespace} 
);

CREATE TABLE CMS_BACKUP_PROPERTYDEF ( 
	PROPERTYDEF_ID INT NOT NULL,
	PROPERTYDEF_NAME VARCHAR2(128) NOT NULL,
	RESOURCE_TYPE INT NOT NULL,
	CONSTRAINT PK_BACKUP_PROPERTYDEF PRIMARY KEY(PROPERTYDEF_ID) USING INDEX TABLESPACE ${indexTablespace} ,
	CONSTRAINT UK_BACKUP_PROPERTYDEF UNIQUE(PROPERTYDEF_NAME, RESOURCE_TYPE) USING INDEX TABLESPACE ${indexTablespace} 
);

CREATE TABLE CMS_OFFLINE_PROPERTIES (
	PROPERTY_ID INT NOT NULL,
	PROPERTYDEF_ID INT NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_NAME VARCHAR2(1024) NOT NULL,
	PROPERTY_VALUE VARCHAR2(2048) NOT NULL,
	CONSTRAINT PK_OFFLINE_PROPERTIES PRIMARY KEY(PROPERTY_ID) USING INDEX TABLESPACE ${indexTablespace}
	STORAGE ( FREELISTS 10 )
);

CREATE TABLE CMS_ONLINE_PROPERTIES (
	PROPERTY_ID INT NOT NULL,
	PROPERTYDEF_ID INT NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_NAME VARCHAR2(1024) NOT NULL,	
	PROPERTY_VALUE VARCHAR2(2048) NOT NULL,
	CONSTRAINT PK_ONLINE_PROPERTIES PRIMARY KEY(PROPERTY_ID) USING INDEX TABLESPACE ${indexTablespace}
	STORAGE ( FREELISTS 10 )
);

CREATE TABLE CMS_BACKUP_PROPERTIES (
    BACKUP_ID VARCHAR2(36) NOT NULL,
	PROPERTY_ID INT NOT NULL,
	PROPERTYDEF_ID INT NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_NAME VARCHAR2(1024) NOT NULL,	
	PROPERTY_VALUE VARCHAR2(2048) NOT NULL,
	TAG_ID INT,
	VERSION_ID INT NOT NULL,
	CONSTRAINT PK_BACKUP_PROPERTIES PRIMARY KEY(PROPERTY_ID) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_OFFLINE_RESOURCES (
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_TYPE INT NOT NULL,
	RESOURCE_FLAGS INT NOT NULL,
	FILE_ID VARCHAR2(36) NOT NULL,
	LOADER_TYPE INT NOT NULL,
	DATE_CREATED DATE NOT NULL,
	DATE_LASTMODIFIED DATE NOT NULL,
	USER_CREATED VARCHAR2(36) NOT NULL,
	USER_LASTMODIFIED VARCHAR2(36) NOT NULL,
	USER_LOCK VARCHAR2(36) NOT NULL,
	PROJECT_ID INT NOT NULL,
	RESOURCE_STATE INT NOT NULL,
	RESOURCE_SIZE INT NOT NULL,
	LINK_COUNT INT NOT NULL,
	CONSTRAINT PK_OFFLINE_RESOURCES PRIMARY KEY(RESOURCE_ID) USING INDEX TABLESPACE ${indexTablespace}
	STORAGE ( FREELISTS 10 )
);

CREATE TABLE CMS_ONLINE_RESOURCES (
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_TYPE INT NOT NULL,
	RESOURCE_FLAGS INT NOT NULL,
	FILE_ID VARCHAR2(36) NOT NULL,
	LOADER_TYPE INT NOT NULL,
	DATE_CREATED DATE NOT NULL,
	DATE_LASTMODIFIED DATE NOT NULL,
	USER_CREATED VARCHAR2(36) NOT NULL,
	USER_LASTMODIFIED VARCHAR2(36) NOT NULL,
	USER_LOCK VARCHAR2(36) NOT NULL,
	PROJECT_ID INT NOT NULL,
	RESOURCE_STATE INT NOT NULL,
	RESOURCE_SIZE INT NOT NULL,
	LINK_COUNT INT NOT NULL,
	CONSTRAINT PK_ONLINE_RESOURCES PRIMARY KEY(RESOURCE_ID) USING INDEX TABLESPACE ${indexTablespace}
	STORAGE ( FREELISTS 10 )
);

CREATE TABLE CMS_BACKUP_RESOURCES (
	BACKUP_ID VARCHAR2(36) NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	RESOURCE_TYPE INT NOT NULL,
	RESOURCE_FLAGS INT NOT NULL,
	FILE_ID VARCHAR2(36) NOT NULL,
	LOADER_TYPE INT NOT NULL,
	DATE_CREATED DATE NOT NULL,
	DATE_LASTMODIFIED DATE NOT NULL,
	USER_CREATED VARCHAR2(36) NOT NULL,
	USER_LASTMODIFIED VARCHAR2(36) NOT NULL,
	USER_LOCK VARCHAR2(36) NOT NULL,
	PROJECT_ID INT NOT NULL,
	RESOURCE_STATE INT NOT NULL,
	RESOURCE_SIZE INT NOT NULL,
	LINK_COUNT INT NOT NULL,
	TAG_ID INT NOT NULL,
	VERSION_ID INT NOT NULL,
    USER_CREATED_NAME VARCHAR2(64) NOT NULL,
    USER_LASTMODIFIED_NAME VARCHAR2(64) NOT NULL,
	CONSTRAINT PK_BACKUP_RESOURCES PRIMARY KEY(BACKUP_ID) USING INDEX TABLESPACE ${indexTablespace} ,
	CONSTRAINT UK_BACKUP_RESOURCES UNIQUE(TAG_ID,RESOURCE_ID) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_OFFLINE_FILES (
	FILE_ID VARCHAR2(36) NOT NULL,
	FILE_CONTENT blob NOT NULL,
	CONSTRAINT PK_OFFLINE_FILES PRIMARY KEY(FILE_ID) USING INDEX TABLESPACE ${indexTablespace}
)
	STORAGE (INITIAL 256K NEXT 1M PCTINCREASE 0)
	LOB(FILE_CONTENT) STORE AS (
        CHUNK 32K PCTVERSION 20  
        CACHE
);

CREATE TABLE CMS_ONLINE_FILES (
	FILE_ID VARCHAR2(36) NOT NULL,
	FILE_CONTENT blob NOT NULL,
	CONSTRAINT PK_ONLINE_FILES PRIMARY KEY(FILE_ID) USING INDEX TABLESPACE ${indexTablespace}
)
	STORAGE (INITIAL 256K NEXT 1M PCTINCREASE 0)
	LOB(FILE_CONTENT) STORE AS (
        CHUNK 32K PCTVERSION 20  
        CACHE
);

CREATE TABLE CMS_BACKUP_FILES (
	BACKUP_ID VARCHAR2(36) NOT NULL,
	FILE_ID VARCHAR2(36) NOT NULL,
	FILE_CONTENT blob NOT NULL,
	TAG_ID INT,
	VERSION_ID INT NOT NULL,
	CONSTRAINT PK_BACKUP_FILES PRIMARY KEY(BACKUP_ID) USING INDEX TABLESPACE ${indexTablespace}
)	
	STORAGE (INITIAL 256K NEXT 1M PCTINCREASE 0)
	LOB(FILE_CONTENT) STORE AS (
        CHUNK 32K PCTVERSION 20  
        CACHE
);

CREATE TABLE CMS_GROUPS (
	GROUP_ID VARCHAR2(36) NOT NULL,
	PARENT_GROUP_ID VARCHAR2(36) NOT NULL,
	GROUP_NAME VARCHAR2(64) NOT NULL,
	GROUP_DESCRIPTION VARCHAR2(255) NOT NULL,
	GROUP_FLAGS INT NOT NULL,
	CONSTRAINT PK_GROUPS PRIMARY KEY(GROUP_ID) USING INDEX TABLESPACE ${indexTablespace} ,
	CONSTRAINT UK_GROUPS UNIQUE(GROUP_NAME) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_SYSTEMID (
	TABLE_KEY VARCHAR2(255) NOT NULL,
	ID INT NOT NULL,
	CONSTRAINT PK_SYSTEMID PRIMARY KEY(TABLE_KEY) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_EXPORT_DEPENDENCIES (
	LINK_ID INT NOT NULL,
	RESOURCENAME VARCHAR2(255),
	CONSTRAINT UK_EXPORT_DEPENDENCIES UNIQUE(LINK_ID, RESOURCENAME) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_GROUPUSERS (
	GROUP_ID VARCHAR2(36) NOT NULL,
	USER_ID VARCHAR2(36) NOT NULL,
	GROUPUSER_FLAGS INT NOT NULL,
	CONSTRAINT UK_GROUPUSERS UNIQUE(GROUP_ID, USER_ID) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_Task ( 
	autofinish INT, 
	endtime DATE, 
	escalationtyperef INT, 
	id INT NOT NULL, 
	initiatoruserref VARCHAR2(36), 
	milestoneref INT, 
	name varchar(254), 
	originaluserref VARCHAR2(36), 
	agentuserref VARCHAR2(36), 
	parent INT, 
	percentage varchar(50), 
	permission varchar(50), 
	priorityref INT DEFAULT '2', 
	roleref VARCHAR2(36), 
	root INT, 
	starttime DATE, 
	state INT, 
	tasktyperef INT, 
	timeout DATE, 
	wakeuptime DATE, 
	htmllink varchar(254), 
	estimatetime INT DEFAULT '86400', 
	CONSTRAINT PK_TASK PRIMARY KEY(id) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_TaskType (
	autofinish INT, 
	escalationtyperef INT, 
	htmllink varchar(254), 
	id INT NOT NULL, 
	name varchar(50), 
	permission varchar(50), 
	priorityref INT, 
	roleref VARCHAR2(36), 
	CONSTRAINT PK_TASKTYPE PRIMARY KEY(id) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_TaskLog (
	coment long, 
	externalusername varchar(254), 
	id INT NOT NULL, 
	starttime DATE, 
	taskref INT, 
	userref INT, 
	type INT DEFAULT '0', 
	CONSTRAINT PK_TASKLOG PRIMARY KEY(id) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_TaskPar (
	id INT NOT NULL, 
	parname varchar(50), 
	parvalue varchar(50), 
	ref INT, 
	CONSTRAINT PK_TASKPAR PRIMARY KEY(id) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_MODULE_ONLINE_MASTER (
	MASTER_ID VARCHAR2(36) NOT NULL,
	SUB_ID NUMBER NOT NULL,
	USER_ID VARCHAR2(36) NOT NULL,
	GROUP_ID VARCHAR2(36) NOT NULL,
	PROJECT_ID NUMBER NOT NULL,
	ACCESS_FLAGS NUMBER NOT NULL,
	STATE NUMBER NOT NULL,
	LOCKED_BY VARCHAR2(36) NOT NULL,
	LASTMODIFIED_BY VARCHAR2(36) NOT NULL,
	DATE_CREATED DATE NOT NULL,
	DATE_LASTMODIFIED DATE NOT NULL,
	PUBLICATION_DATE DATE,
	PURGE_DATE DATE,
	FLAGS NUMBER,
	FEED_ID NUMBER,
	FEED_REFERENCE NUMBER,
	FEED_FILENAME VARCHAR2(255),
	TITLE VARCHAR2(255),
	DATA_BIG_0 VARCHAR2(4000),
	DATA_BIG_1 VARCHAR2(4000),
	DATA_BIG_2 VARCHAR2(4000),
	DATA_BIG_3 VARCHAR2(4000),
	DATA_BIG_4 VARCHAR2(4000),
	DATA_BIG_5 VARCHAR2(4000),
	DATA_BIG_6 VARCHAR2(4000),
	DATA_BIG_7 VARCHAR2(4000),
	DATA_BIG_8 VARCHAR2(4000),
	DATA_BIG_9 VARCHAR2(4000),
	DATA_MEDIUM_0 VARCHAR2(2000),
	DATA_MEDIUM_1 VARCHAR2(2000),
	DATA_MEDIUM_2 VARCHAR2(2000),
	DATA_MEDIUM_3 VARCHAR2(2000),
	DATA_MEDIUM_4 VARCHAR2(2000),
	DATA_MEDIUM_5 VARCHAR2(2000),
	DATA_MEDIUM_6 VARCHAR2(2000),
	DATA_MEDIUM_7 VARCHAR2(2000),
	DATA_MEDIUM_8 VARCHAR2(2000),
	DATA_MEDIUM_9 VARCHAR2(2000),
	DATA_SMALL_0 VARCHAR2(500),
	DATA_SMALL_1 VARCHAR2(500),
	DATA_SMALL_2 VARCHAR2(500),
	DATA_SMALL_3 VARCHAR2(500),
	DATA_SMALL_4 VARCHAR2(500),
	DATA_SMALL_5 VARCHAR2(500),
	DATA_SMALL_6 VARCHAR2(500),
	DATA_SMALL_7 VARCHAR2(500),
	DATA_SMALL_8 VARCHAR2(500),
	DATA_SMALL_9 VARCHAR2(500),
	DATA_SMALL_10 VARCHAR2(500),
	DATA_SMALL_11 VARCHAR2(500),
	DATA_SMALL_12 VARCHAR2(500),
	DATA_SMALL_13 VARCHAR2(500),
	DATA_SMALL_14 VARCHAR2(500),
	DATA_SMALL_15 VARCHAR2(500),
	DATA_SMALL_16 VARCHAR2(500),
	DATA_SMALL_17 VARCHAR2(500),
	DATA_SMALL_18 VARCHAR2(500),
	DATA_SMALL_19 VARCHAR2(500),
	DATA_SMALL_20 VARCHAR2(500),
	DATA_SMALL_21 VARCHAR2(500),
	DATA_SMALL_22 VARCHAR2(500),
	DATA_SMALL_23 VARCHAR2(500),
	DATA_SMALL_24 VARCHAR2(500),
	DATA_SMALL_25 VARCHAR2(500),
	DATA_SMALL_26 VARCHAR2(500),
	DATA_SMALL_27 VARCHAR2(500),
	DATA_SMALL_28 VARCHAR2(500),
	DATA_SMALL_29 VARCHAR2(500),
	DATA_SMALL_30 VARCHAR2(500),
	DATA_SMALL_31 VARCHAR2(500),
	DATA_SMALL_32 VARCHAR2(500),
	DATA_SMALL_33 VARCHAR2(500),
	DATA_SMALL_34 VARCHAR2(500),
	DATA_SMALL_35 VARCHAR2(500),
	DATA_SMALL_36 VARCHAR2(500),
	DATA_SMALL_37 VARCHAR2(500),
	DATA_SMALL_38 VARCHAR2(500),
	DATA_SMALL_39 VARCHAR2(500),
	DATA_INT_0 NUMBER,
	DATA_INT_1 NUMBER,
	DATA_INT_2 NUMBER,
	DATA_INT_3 NUMBER,
	DATA_INT_4 NUMBER,
	DATA_INT_5 NUMBER,
	DATA_INT_6 NUMBER,
	DATA_INT_7 NUMBER,
	DATA_INT_8 NUMBER,
	DATA_INT_9 NUMBER,
	DATA_REFERENCE_0 NUMBER,
	DATA_REFERENCE_1 NUMBER,
	DATA_REFERENCE_2 NUMBER,
	DATA_REFERENCE_3 NUMBER,
	DATA_REFERENCE_4 NUMBER,
	DATA_REFERENCE_5 NUMBER,
	DATA_REFERENCE_6 NUMBER,
	DATA_REFERENCE_7 NUMBER,
	DATA_REFERENCE_8 NUMBER,
	DATA_REFERENCE_9 NUMBER,
	DATA_DATE_0 DATE,
	DATA_DATE_1 DATE,
	DATA_DATE_2 DATE,
	DATA_DATE_3 DATE,
	DATA_DATE_4 DATE,
	CONSTRAINT PK_MODULE_ONLINE_MASTER PRIMARY KEY(MASTER_ID) USING INDEX TABLESPACE ${indexTablespace}
);
                                         
CREATE TABLE CMS_MODULE_ONLINE_CHANNEL_REL (
	MASTER_ID VARCHAR2(36) NOT NULL,
	CHANNEL_ID VARCHAR2(36) NOT NULL,
    CHANNEL_NAME VARCHAR2(1024) NOT NULL,
	CONSTRAINT PK_MODULE_ONLINE_CHANNEL_REL PRIMARY KEY(CHANNEL_ID, MASTER_ID) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_MODULE_ONLINE_MEDIA (
	MEDIA_ID NUMBER NOT NULL,
	MASTER_ID VARCHAR2(36) NOT NULL,
	MEDIA_POSITION NUMBER NOT NULL,
	MEDIA_WIDTH NUMBER NOT NULL,
	MEDIA_HEIGHT NUMBER NOT NULL,
	MEDIA_SIZE NUMBER NOT NULL,
	MEDIA_MIMETYPE VARCHAR2(255),
	MEDIA_TYPE NUMBER NOT NULL,
	MEDIA_TITLE VARCHAR2(255),
	MEDIA_NAME VARCHAR2(255),
	MEDIA_DESCRIPTION VARCHAR2(500) NOT NULL,
	MEDIA LONG RAW NOT NULL,
	CONSTRAINT PK_MODULE_ONLINE_MEDIA PRIMARY KEY(MEDIA_ID) USING INDEX TABLESPACE ${indexTablespace}
);
                                         
CREATE TABLE CMS_MODULE_MASTER (
	MASTER_ID VARCHAR2(36) NOT NULL,
	SUB_ID NUMBER NOT NULL,
	USER_ID VARCHAR2(36) NOT NULL,
	GROUP_ID VARCHAR2(36) NOT NULL,
	PROJECT_ID NUMBER NOT NULL,
	ACCESS_FLAGS NUMBER NOT NULL,
	STATE NUMBER NOT NULL,
	LOCKED_BY VARCHAR2(36) NOT NULL,
	LASTMODIFIED_BY VARCHAR2(36) NOT NULL,
	DATE_CREATED DATE NOT NULL,
	DATE_LASTMODIFIED DATE NOT NULL,
	PUBLICATION_DATE DATE,
	PURGE_DATE DATE,
	FLAGS NUMBER,
	FEED_ID NUMBER,
	FEED_REFERENCE NUMBER,
	FEED_FILENAME VARCHAR2(255),
	TITLE VARCHAR2(255),
	DATA_BIG_0 VARCHAR2(4000),
	DATA_BIG_1 VARCHAR2(4000),
	DATA_BIG_2 VARCHAR2(4000),
	DATA_BIG_3 VARCHAR2(4000),
	DATA_BIG_4 VARCHAR2(4000),
	DATA_BIG_5 VARCHAR2(4000),
	DATA_BIG_6 VARCHAR2(4000),
	DATA_BIG_7 VARCHAR2(4000),
	DATA_BIG_8 VARCHAR2(4000),
	DATA_BIG_9 VARCHAR2(4000),
	DATA_MEDIUM_0 VARCHAR2(2000),
	DATA_MEDIUM_1 VARCHAR2(2000),
	DATA_MEDIUM_2 VARCHAR2(2000),
	DATA_MEDIUM_3 VARCHAR2(2000),
	DATA_MEDIUM_4 VARCHAR2(2000),
	DATA_MEDIUM_5 VARCHAR2(2000),
	DATA_MEDIUM_6 VARCHAR2(2000),
	DATA_MEDIUM_7 VARCHAR2(2000),
	DATA_MEDIUM_8 VARCHAR2(2000),
	DATA_MEDIUM_9 VARCHAR2(2000),
	DATA_SMALL_0 VARCHAR2(500),
	DATA_SMALL_1 VARCHAR2(500),
	DATA_SMALL_2 VARCHAR2(500),
	DATA_SMALL_3 VARCHAR2(500),
	DATA_SMALL_4 VARCHAR2(500),
	DATA_SMALL_5 VARCHAR2(500),
	DATA_SMALL_6 VARCHAR2(500),
	DATA_SMALL_7 VARCHAR2(500),
	DATA_SMALL_8 VARCHAR2(500),
	DATA_SMALL_9 VARCHAR2(500),
	DATA_SMALL_10 VARCHAR2(500),
	DATA_SMALL_11 VARCHAR2(500),
	DATA_SMALL_12 VARCHAR2(500),
	DATA_SMALL_13 VARCHAR2(500),
	DATA_SMALL_14 VARCHAR2(500),
	DATA_SMALL_15 VARCHAR2(500),
	DATA_SMALL_16 VARCHAR2(500),
	DATA_SMALL_17 VARCHAR2(500),
	DATA_SMALL_18 VARCHAR2(500),
	DATA_SMALL_19 VARCHAR2(500),
	DATA_SMALL_20 VARCHAR2(500),
	DATA_SMALL_21 VARCHAR2(500),
	DATA_SMALL_22 VARCHAR2(500),
	DATA_SMALL_23 VARCHAR2(500),
	DATA_SMALL_24 VARCHAR2(500),
	DATA_SMALL_25 VARCHAR2(500),
	DATA_SMALL_26 VARCHAR2(500),
	DATA_SMALL_27 VARCHAR2(500),
	DATA_SMALL_28 VARCHAR2(500),
	DATA_SMALL_29 VARCHAR2(500),
	DATA_SMALL_30 VARCHAR2(500),
	DATA_SMALL_31 VARCHAR2(500),
	DATA_SMALL_32 VARCHAR2(500),
	DATA_SMALL_33 VARCHAR2(500),
	DATA_SMALL_34 VARCHAR2(500),
	DATA_SMALL_35 VARCHAR2(500),
	DATA_SMALL_36 VARCHAR2(500),
	DATA_SMALL_37 VARCHAR2(500),
	DATA_SMALL_38 VARCHAR2(500),
	DATA_SMALL_39 VARCHAR2(500),
	DATA_INT_0 NUMBER,
	DATA_INT_1 NUMBER,
	DATA_INT_2 NUMBER,
	DATA_INT_3 NUMBER,
	DATA_INT_4 NUMBER,
	DATA_INT_5 NUMBER,
	DATA_INT_6 NUMBER,
	DATA_INT_7 NUMBER,
	DATA_INT_8 NUMBER,
	DATA_INT_9 NUMBER,
	DATA_REFERENCE_0 NUMBER,
	DATA_REFERENCE_1 NUMBER,
	DATA_REFERENCE_2 NUMBER,
	DATA_REFERENCE_3 NUMBER,
	DATA_REFERENCE_4 NUMBER,
	DATA_REFERENCE_5 NUMBER,
	DATA_REFERENCE_6 NUMBER,
	DATA_REFERENCE_7 NUMBER,
	DATA_REFERENCE_8 NUMBER,
	DATA_REFERENCE_9 NUMBER,
	DATA_DATE_0 DATE,
	DATA_DATE_1 DATE,
	DATA_DATE_2 DATE,
	DATA_DATE_3 DATE,
	DATA_DATE_4 DATE,
	CONSTRAINT PK_MODULE_MASTER PRIMARY KEY(MASTER_ID) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_MODULE_CHANNEL_REL (
	MASTER_ID VARCHAR2(36) NOT NULL,
	CHANNEL_ID VARCHAR2(36) NOT NULL,
	CHANNEL_NAME VARCHAR2(1024) NOT NULL,
	CONSTRAINT PK_MODULE_CHANNEL_REL PRIMARY KEY(CHANNEL_ID, MASTER_ID) USING INDEX TABLESPACE ${indexTablespace}
);


CREATE TABLE CMS_MODULE_MEDIA (
	MEDIA_ID NUMBER NOT NULL,
	MASTER_ID VARCHAR2(36) NOT NULL,
	MEDIA_POSITION NUMBER NOT NULL,
	MEDIA_WIDTH NUMBER NOT NULL,
	MEDIA_HEIGHT NUMBER NOT NULL,
	MEDIA_SIZE NUMBER NOT NULL,
	MEDIA_MIMETYPE VARCHAR2(255),
	MEDIA_TYPE NUMBER NOT NULL,
	MEDIA_TITLE VARCHAR2(255),
	MEDIA_NAME VARCHAR2(255),
	MEDIA_DESCRIPTION VARCHAR2(500) NOT NULL,
	MEDIA LONG RAW NOT NULL,
	CONSTRAINT PK_MODULE_MEDIA PRIMARY KEY(MEDIA_ID) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_MODULE_BACKUP_MASTER (
	MASTER_ID VARCHAR2(36) NOT NULL,
	SUB_ID NUMBER NOT NULL,
	USER_ID VARCHAR2(36) NOT NULL,
	GROUP_ID VARCHAR2(36) NOT NULL,
	PROJECT_ID NUMBER NOT NULL,
	ACCESS_FLAGS NUMBER NOT NULL,
	STATE NUMBER NOT NULL,
	LOCKED_BY VARCHAR2(36) NOT NULL,
	LASTMODIFIED_BY VARCHAR2(36) NOT NULL,
	DATE_CREATED DATE NOT NULL,
	DATE_LASTMODIFIED DATE NOT NULL,
	PUBLICATION_DATE DATE,
	PURGE_DATE DATE,
	FLAGS NUMBER,
	FEED_ID NUMBER,
	FEED_REFERENCE NUMBER,
	FEED_FILENAME VARCHAR2(255),
	TITLE VARCHAR2(255),
	DATA_BIG_0 VARCHAR2(4000),
	DATA_BIG_1 VARCHAR2(4000),
	DATA_BIG_2 VARCHAR2(4000),
	DATA_BIG_3 VARCHAR2(4000),
	DATA_BIG_4 VARCHAR2(4000),
	DATA_BIG_5 VARCHAR2(4000),
	DATA_BIG_6 VARCHAR2(4000),
	DATA_BIG_7 VARCHAR2(4000),
	DATA_BIG_8 VARCHAR2(4000),
	DATA_BIG_9 VARCHAR2(4000),
	DATA_MEDIUM_0 VARCHAR2(2000),
	DATA_MEDIUM_1 VARCHAR2(2000),
	DATA_MEDIUM_2 VARCHAR2(2000),
	DATA_MEDIUM_3 VARCHAR2(2000),
	DATA_MEDIUM_4 VARCHAR2(2000),
	DATA_MEDIUM_5 VARCHAR2(2000),
	DATA_MEDIUM_6 VARCHAR2(2000),
	DATA_MEDIUM_7 VARCHAR2(2000),
	DATA_MEDIUM_8 VARCHAR2(2000),
	DATA_MEDIUM_9 VARCHAR2(2000),
	DATA_SMALL_0 VARCHAR2(500),
	DATA_SMALL_1 VARCHAR2(500),
	DATA_SMALL_2 VARCHAR2(500),
	DATA_SMALL_3 VARCHAR2(500),
	DATA_SMALL_4 VARCHAR2(500),
	DATA_SMALL_5 VARCHAR2(500),
	DATA_SMALL_6 VARCHAR2(500),
	DATA_SMALL_7 VARCHAR2(500),
	DATA_SMALL_8 VARCHAR2(500),
	DATA_SMALL_9 VARCHAR2(500),
	DATA_SMALL_10 VARCHAR2(500),
	DATA_SMALL_11 VARCHAR2(500),
	DATA_SMALL_12 VARCHAR2(500),
	DATA_SMALL_13 VARCHAR2(500),
	DATA_SMALL_14 VARCHAR2(500),
	DATA_SMALL_15 VARCHAR2(500),
	DATA_SMALL_16 VARCHAR2(500),
	DATA_SMALL_17 VARCHAR2(500),
	DATA_SMALL_18 VARCHAR2(500),
	DATA_SMALL_19 VARCHAR2(500),
	DATA_SMALL_20 VARCHAR2(500),
	DATA_SMALL_21 VARCHAR2(500),
	DATA_SMALL_22 VARCHAR2(500),
	DATA_SMALL_23 VARCHAR2(500),
	DATA_SMALL_24 VARCHAR2(500),
	DATA_SMALL_25 VARCHAR2(500),
	DATA_SMALL_26 VARCHAR2(500),
	DATA_SMALL_27 VARCHAR2(500),
	DATA_SMALL_28 VARCHAR2(500),
	DATA_SMALL_29 VARCHAR2(500),
	DATA_SMALL_30 VARCHAR2(500),
	DATA_SMALL_31 VARCHAR2(500),
	DATA_SMALL_32 VARCHAR2(500),
	DATA_SMALL_33 VARCHAR2(500),
	DATA_SMALL_34 VARCHAR2(500),
	DATA_SMALL_35 VARCHAR2(500),
	DATA_SMALL_36 VARCHAR2(500),
	DATA_SMALL_37 VARCHAR2(500),
	DATA_SMALL_38 VARCHAR2(500),
	DATA_SMALL_39 VARCHAR2(500),
	DATA_INT_0 NUMBER,
	DATA_INT_1 NUMBER,
	DATA_INT_2 NUMBER,
	DATA_INT_3 NUMBER,
	DATA_INT_4 NUMBER,
	DATA_INT_5 NUMBER,
	DATA_INT_6 NUMBER,
	DATA_INT_7 NUMBER,
	DATA_INT_8 NUMBER,
	DATA_INT_9 NUMBER,
	DATA_REFERENCE_0 NUMBER,
	DATA_REFERENCE_1 NUMBER,
	DATA_REFERENCE_2 NUMBER,
	DATA_REFERENCE_3 NUMBER,
	DATA_REFERENCE_4 NUMBER,
	DATA_REFERENCE_5 NUMBER,
	DATA_REFERENCE_6 NUMBER,
	DATA_REFERENCE_7 NUMBER,
	DATA_REFERENCE_8 NUMBER,
	DATA_REFERENCE_9 NUMBER,
	DATA_DATE_0 DATE,
	DATA_DATE_1 DATE,
	DATA_DATE_2 DATE,
	DATA_DATE_3 DATE,
	DATA_DATE_4 DATE,
	TAG_ID NUMBER NOT NULL,
	USER_NAME VARCHAR(167),
	GROUP_NAME VARCHAR(64),
	LASTMODIFIED_BY_NAME VARCHAR(167),
	CONSTRAINT PK_MODULE_BACKUP_MASTER PRIMARY KEY(MASTER_ID, TAG_ID) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_MODULE_BACKUP_MEDIA (
	MEDIA_ID NUMBER NOT NULL,
	MASTER_ID VARCHAR2(36) NOT NULL,
	MEDIA_POSITION NUMBER NOT NULL,
	MEDIA_WIDTH NUMBER NOT NULL,
	MEDIA_HEIGHT NUMBER NOT NULL,
	MEDIA_SIZE NUMBER NOT NULL,
	MEDIA_MIMETYPE VARCHAR2(255),
	MEDIA_TYPE NUMBER NOT NULL,
	MEDIA_TITLE VARCHAR2(255),
	MEDIA_NAME VARCHAR2(255),
	MEDIA_DESCRIPTION VARCHAR2(500) NOT NULL,
	MEDIA LONG RAW NOT NULL,
	TAG_ID NUMBER NOT NULL,
	CONSTRAINT PK_MODULE_BACKUP_MEDIA PRIMARY KEY(MEDIA_ID, TAG_ID) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_WEBUSERS (  
	USER_ID VARCHAR2(36) NOT NULL,
	USER_MEMBER_ID VARCHAR(255),
	USER_SALUTATION VARCHAR(255),
	USER_TITLE VARCHAR(255),
	USER_PWD VARCHAR(255),   
	USER_PWD_QUESTION VARCHAR(255),   
	USER_PWD_ANSWER VARCHAR(255),        
	USER_CITY VARCHAR(255),
	USER_POSTCODE VARCHAR(255),
	USER_STATE VARCHAR(255),
	USER_COUNTRY VARCHAR(255),
	USER_ADDRESS_TYPE INT,
	USER_BIRTHDAY DATE,
	USER_PHONE VARCHAR(255),
	USER_FAX VARCHAR(255),
	USER_MOBILE VARCHAR(255),
	USER_ACCEPT INT,   
	USER_RECOMMENDED_BY	VARCHAR(255), 
	USER_PROFESSION VARCHAR(255),
	USER_COMPANY VARCHAR(255),
	USER_DEPARTMENT VARCHAR(255),
	USER_POSITION VARCHAR(255),         
	USER_ACCOUNT_NUMBER VARCHAR(255),
	USER_BANK_NUMBER VARCHAR(255),
	USER_BANK VARCHAR(255),
	USER_NEWSLETTER VARCHAR(255),   
	USER_EXTRAINFO_1 VARCHAR(255),
	USER_EXTRAINFO_2 VARCHAR(255),
	USER_EXTRAINFO_3 VARCHAR(255),
	USER_EXTRAINFO_4 VARCHAR(255),
	USER_EXTRAINFO_5 VARCHAR(255),
	USER_EXTRAINFO_6 VARCHAR(255),
	USER_EXTRAINFO_7 VARCHAR(255),
	USER_EXTRAINFO_8 VARCHAR(255),
	USER_EXTRAINFO_9 VARCHAR(255),
	USER_EXTRAINFO_10 VARCHAR(255),
	USER_EXTRAINFO_11 VARCHAR(255),
	USER_EXTRAINFO_12 VARCHAR(255),
	USER_EXTRAINFO_13 VARCHAR(255),
	USER_EXTRAINFO_14 VARCHAR(255),
	USER_EXTRAINFO_15 VARCHAR(255),
	USER_EXTRAINFO_16 VARCHAR(255),
	USER_EXTRAINFO_17 VARCHAR(255),
	USER_EXTRAINFO_18 VARCHAR(255),
	USER_EXTRAINFO_19 BLOB,
	USER_EXTRAINFO_20 BLOB,
	USER_PICTURE BLOB,
	USER_PICTURE_NAME VARCHAR(255),         
	USER_CREATE_DATE DATE,
	USER_LASTCHANGE_BY VARCHAR(255),
	USER_LASTCHANGE_DATE DATE,
	LOCKSTATE INT,
	CONSTRAINT PK_WEBUSERS PRIMARY KEY (USER_ID) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_ONLINE_ACCESSCONTROL (
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	PRINCIPAL_ID VARCHAR2(36) NOT NULL,
	ACCESS_ALLOWED INT,
	ACCESS_DENIED INT,
	ACCESS_FLAGS INT,
	CONSTRAINT PK_ONLINE_ACCESSCONTROL PRIMARY KEY(RESOURCE_ID, PRINCIPAL_ID) USING INDEX TABLESPACE ${indexTablespace}
);
   
CREATE TABLE CMS_OFFLINE_ACCESSCONTROL (
	RESOURCE_ID VARCHAR2(36) NOT NULL,
	PRINCIPAL_ID VARCHAR2(36) NOT NULL,
	ACCESS_ALLOWED INT,
	ACCESS_DENIED INT,
	ACCESS_FLAGS INT,
	CONSTRAINT PK_OFFLINE_ACCESSCONTROL PRIMARY KEY(RESOURCE_ID, PRINCIPAL_ID) USING INDEX TABLESPACE ${indexTablespace}
);
   
CREATE TABLE CMS_OFFLINE_STRUCTURE (
	STRUCTURE_ID VARCHAR2(36) NOT NULL,
	PARENT_ID VARCHAR2(36) NOT NULL,
	RESOURCE_ID VARCHAR(236) NOT NULL,	
	RESOURCE_NAME VARCHAR2(1024) NOT NULL,
	STRUCTURE_STATE INT NOT NULL,	
	CONSTRAINT PK_OFFLINE_STRUCTURE PRIMARY KEY (STRUCTURE_ID) USING INDEX TABLESPACE ${indexTablespace}
	STORAGE ( FREELISTS 10 )
);

CREATE TABLE CMS_ONLINE_STRUCTURE (
	STRUCTURE_ID VARCHAR2(36) NOT NULL,
	PARENT_ID VARCHAR2(36) NOT NULL,
	RESOURCE_ID VARCHAR(236) NOT NULL,	
	RESOURCE_NAME VARCHAR2(1024) NOT NULL,
	STRUCTURE_STATE INT NOT NULL,	
	CONSTRAINT PK_ONLINE_STRUCTURE PRIMARY KEY (STRUCTURE_ID) USING INDEX TABLESPACE ${indexTablespace}
	STORAGE ( FREELISTS 10 )
);

CREATE TABLE CMS_BACKUP_STRUCTURE (
	BACKUP_ID VARCHAR2(36) NOT NULL,
    TAG_ID INT NOT NULL,
    VERSION_ID INT NOT NULL,
	STRUCTURE_ID VARCHAR2(36) NOT NULL,
	PARENT_ID VARCHAR2(36) NOT NULL,
	RESOURCE_ID VARCHAR2(36) NOT NULL,	
	RESOURCE_NAME VARCHAR2(1024) NOT NULL,
	STRUCTURE_STATE INT NOT NULL,
	CONSTRAINT PK_BACKUP_STRUCTURE PRIMARY KEY (BACKUP_ID) USING INDEX TABLESPACE ${indexTablespace}
);     

CREATE TABLE CMS_PUBLISH_HISTORY (
	PUBLISH_ID			VARCHAR(36) NOT NULL,
	TAG_ID				INT NOT NULL,
	STRUCTURE_ID		VARCHAR2(36) NOT NULL,
	RESOURCE_ID			VARCHAR2(36) NOT NULL,
	CONTENT_ID			VARCHAR2(36) NOT NULL,
	RESOURCE_NAME		VARCHAR2(1024),
	RESOURCE_STATE		INT NOT NULL,
	RESOURCE_TYPE		INT NOT NULL,
	SIBLING_COUNT		INT NOT NULL,
	MASTER_ID			VARCHAR(36) NOT NULL,
	CONTENT_DEFINITION_NAME		VARCHAR(128),	
	CONSTRAINT PK_PUBLISH_HISTORY PRIMARY KEY (PUBLISH_ID, TAG_ID, STRUCTURE_ID, MASTER_ID) USING INDEX TABLESPACE ${indexTablespace}
);

CREATE TABLE CMS_PUBLISHED_RESOURCES (
	PUBLISHED_ID				VARCHAR(36) NOT NULL,
	RESOURCE_NAME				VARCHAR2(1024),
	LINK_TYPE					INT NOT NULL,
	LINK_PARAMETER			    VARCHAR2(1024),
	PRIMARY KEY					(PUBLISHED_ID)	
	CONSTRAINT CMS_PUBLISHED_RESOURCES PRIMARY KEY (PUBLISHED_ID) USING INDEX TABLESPACE ${indexTablespace}
);


CREATE INDEX IDX_PUBLISH_HISTORY_01 ON CMS_PUBLISH_HISTORY(PUBLISH_ID);

CREATE INDEX IDX_GROUPS_01 
	ON CMS_GROUPS(PARENT_GROUP_ID)
	TABLESPACE ${indexTablespace};

CREATE INDEX IDX_GROUPUSERS_01 
	ON CMS_GROUPUSERS(GROUP_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_GROUPUSERS_02 
	ON CMS_GROUPUSERS(USER_ID)
	TABLESPACE ${indexTablespace};

CREATE INDEX IDX_PROJECTS_01 
	ON CMS_PROJECTS(GROUP_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_PROJECTS_02 
	ON CMS_PROJECTS(MANAGERGROUP_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_PROJECTS_03 
	ON CMS_PROJECTS(USER_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_PROJECTS_04 
	ON CMS_PROJECTS(PROJECT_NAME)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_PROJECTS_05 
	ON CMS_PROJECTS(TASK_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_PROJECTS_06 
	ON CMS_PROJECTS (PROJECT_FLAGS)
	TABLESPACE ${indexTablespace};

CREATE INDEX IDX_OFFLINE_RESOURCES_01 
	ON CMS_OFFLINE_RESOURCES (RESOURCE_ID,RESOURCE_TYPE)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_RESOURCES_02 
	ON CMS_OFFLINE_RESOURCES (RESOURCE_ID,FILE_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_RESOURCES_03 
	ON CMS_OFFLINE_RESOURCES (FILE_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_RESOURCES_04
	ON CMS_OFFLINE_RESOURCES (RESOURCE_ID, RESOURCE_STATE)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_RESOURCES_05
	ON CMS_OFFLINE_RESOURCES (DATE_LASTMODIFIED)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_RESOURCES_06
	ON CMS_OFFLINE_RESOURCES (RESOURCE_ID, DATE_LASTMODIFIED)
	TABLESPACE ${indexTablespace};
  
CREATE INDEX IDX_ONLINE_RESOURCES_01 
	ON CMS_ONLINE_RESOURCES (RESOURCE_ID,RESOURCE_TYPE)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_RESOURCES_02 
	ON CMS_ONLINE_RESOURCES (RESOURCE_ID,FILE_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_RESOURCES_03 
	ON CMS_ONLINE_RESOURCES (FILE_ID)
	TABLESPACE ${indexTablespace};

CREATE INDEX IDX_ONLINE_RESOURCES_04
	ON CMS_ONLINE_RESOURCES (RESOURCE_ID, RESOURCE_STATE)
	TABLESPACE ${indexTablespace};

CREATE INDEX ONLINE_RESOURCES_05
	ON CMS_ONLINE_RESOURCES (DATE_LASTMODIFIED)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_RESOURCES_06
	ON CMS_ONLINE_RESOURCES (RESOURCE_ID, DATE_LASTMODIFIED)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_STRUCTURE_01 
	ON CMS_OFFLINE_STRUCTURE (STRUCTURE_ID, RESOURCE_NAME)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_STRUCTURE_02 
	ON CMS_OFFLINE_STRUCTURE (STRUCTURE_ID, PARENT_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_STRUCTURE_03 
	ON CMS_OFFLINE_STRUCTURE (STRUCTURE_ID, RESOURCE_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_STRUCTURE_04 
	ON CMS_OFFLINE_STRUCTURE (STRUCTURE_ID, STRUCTURE_STATE)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_STRUCTURE_05 
	ON CMS_OFFLINE_STRUCTURE (RESOURCE_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_STRUCTURE_06 
	ON CMS_OFFLINE_STRUCTURE (RESOURCE_NAME, PARENT_ID, RESOURCE_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_STRUCTURE_07 
	ON CMS_OFFLINE_STRUCTURE (STRUCTURE_ID, STRUCTURE_STATE, RESOURCE_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_STRUCTURE_08 
	ON CMS_OFFLINE_STRUCTURE (PARENT_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_STRUCTURE_09 
	ON CMS_OFFLINE_STRUCTURE (PARENT_ID, RESOURCE_ID)
	TABLESPACE ${indexTablespace};

CREATE INDEX IDX_ONLINE_STRUCTURE_01 
	ON CMS_ONLINE_STRUCTURE (STRUCTURE_ID, RESOURCE_NAME)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_STRUCTURE_02 
	ON CMS_ONLINE_STRUCTURE (STRUCTURE_ID, PARENT_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_STRUCTURE_03 
	ON CMS_ONLINE_STRUCTURE (STRUCTURE_ID, RESOURCE_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_STRUCTURE_04 
	ON CMS_ONLINE_STRUCTURE (STRUCTURE_ID, STRUCTURE_STATE)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_STRUCTURE_05 
	ON CMS_ONLINE_STRUCTURE (RESOURCE_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_STRUCTURE_06 
	ON CMS_ONLINE_STRUCTURE (RESOURCE_NAME, PARENT_ID, RESOURCE_ID)
	TABLESPACE ${indexTablespace};
	  
CREATE INDEX IDX_ONLINE_STRUCTURE_07 
	ON CMS_ONLINE_STRUCTURE (STRUCTURE_ID, STRUCTURE_STATE, RESOURCE_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_STRUCTURE_08 
	ON CMS_ONLINE_STRUCTURE (PARENT_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_STRUCTURE_09 
	ON CMS_ONLINE_STRUCTURE (PARENT_ID, RESOURCE_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_BACKUP_STRUCTURE_01
	ON CMS_BACKUP_STRUCTURE (STRUCTURE_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_BACKUP_RESOURCES_01
	ON CMS_BACKUP_RESOURCES (RESOURCE_ID)
	TABLESPACE ${indexTablespace};

CREATE INDEX IDX_OFFLINE_PROPERTIES_01 
	ON CMS_OFFLINE_PROPERTIES (PROPERTYDEF_ID, RESOURCE_ID, RESOURCE_NAME)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_PROPERTIES_02 
	ON CMS_OFFLINE_PROPERTIES (PROPERTYDEF_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_PROPERTIES_03 
	ON CMS_OFFLINE_PROPERTIES (PROPERTYDEF_ID, RESOURCE_ID, PROPERTY_VALUE)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_OFFLINE_PROPERTIES_04
	ON CMS_OFFLINE_PROPERTIES (PROPERTYDEF_ID, RESOURCE_ID)
	TABLESPACE ${indexTablespace};

CREATE INDEX IDX_ONLINE_PROPERTIES_01 
	ON CMS_ONLINE_PROPERTIES (PROPERTYDEF_ID, RESOURCE_ID, RESOURCE_NAME)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_PROPERTIES_02 
	ON CMS_ONLINE_PROPERTIES (PROPERTYDEF_ID)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX INX_ONLINE_PROPERTIES_03 
	ON CMS_ONLINE_PROPERTIES (PROPERTYDEF_ID, RESOURCE_ID, PROPERTY_VALUE)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_PROPERTIES_04
	ON CMS_ONLINE_PROPERTIES (PROPERTYDEF_ID, RESOURCE_ID)
	TABLESPACE ${indexTablespace};

CREATE INDEX IDX_OFFLINE_PROPERTYDEF_01 
	ON CMS_OFFLINE_PROPERTYDEF (PROPERTYDEF_ID, RESOURCE_TYPE)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_ONLINE_PROPERTYDEF_01 
	ON CMS_ONLINE_PROPERTYDEF (PROPERTYDEF_ID, RESOURCE_TYPE)
	TABLESPACE ${indexTablespace};

CREATE INDEX IDX_TASK_01 
	ON CMS_TASK(PARENT)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_TASK_02 
	ON CMS_TASK(TASKTYPEREF)
	TABLESPACE ${indexTablespace};

CREATE INDEX IDX_TASKLOG_01 
	ON CMS_TASKLOG(TASKREF)
	TABLESPACE ${indexTablespace};
	
CREATE INDEX IDX_TASKLOG_02 
	ON CMS_TASKLOG(USERREF)
	TABLESPACE ${indexTablespace};

CREATE INDEX IDX_TASKPAR_01 
	ON CMS_TASKPAR(REF)
	TABLESPACE ${indexTablespace};

CREATE INDEX IDX_PROJECTRESOURCES_01 
	ON CMS_PROJECTRESOURCES(RESOURCE_NAME)
	TABLESPACE ${indexTablespace};

CREATE INDEX MASTER_SUBID 
	ON CMS_MODULE_MASTER(SUB_ID)
	TABLESPACE ${indexTablespace};
  
CREATE INDEX ONLINEMASTER_SUBID 
	ON CMS_MODULE_ONLINE_MASTER(SUB_ID)
	TABLESPACE ${indexTablespace};
  
CREATE INDEX ONLINEMEDIA_MASTERID 
	ON CMS_MODULE_ONLINE_MEDIA(MASTER_ID)
	TABLESPACE ${indexTablespace};
  
CREATE INDEX MEDIA_MASTERID 
	ON CMS_MODULE_MEDIA(MASTER_ID)
	TABLESPACE ${indexTablespace};