CREATE TABLE IF NOT EXISTS CMS_STORAGE (
    HASH VARCHAR(128) BINARY NOT NULL,
    FILE_CONTENT LONGBLOB NOT NULL,
    PRIMARY KEY (HASH)
) CHARACTER SET utf8mb4;

ALTER TABLE CMS_OFFLINE_CONTENTS
    ADD COLUMN STORAGE VARCHAR(32) BINARY AFTER FILE_CONTENT,
    ADD COLUMN HASH VARCHAR(128) BINARY AFTER STORAGE;

CREATE INDEX IDX_CMS_OFFLINE_CONTENTS_HASH ON CMS_OFFLINE_CONTENTS(HASH, STORAGE);

ALTER TABLE CMS_CONTENTS
    ADD COLUMN STORAGE VARCHAR(32) BINARY AFTER FILE_CONTENT,
    ADD COLUMN HASH VARCHAR(128) BINARY AFTER STORAGE;

CREATE INDEX IDX_CMS_CONTENTS_HASH ON CMS_CONTENTS(HASH, STORAGE);

ANALYZE TABLE CMS_CONTENTS, CMS_OFFLINE_CONTENTS, CMS_STORAGE;

SELECT TABLE_NAME, COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_TYPE
FROM information_schema.COLUMNS
WHERE TABLE_NAME IN ('CMS_CONTENTS', 'CMS_OFFLINE_CONTENTS', 'CMS_STORAGE')
AND TABLE_SCHEMA = DATABASE()
ORDER BY TABLE_NAME, ORDINAL_POSITION;
